// [super atualização 2 · LEGADO E DINASTIA] textos en/es da tela Legado, da
// cerimônia da cena e dos cards compartilháveis (chave = PT exato do ct()).
export const LEGADO_STR: Record<string, { en: string; es: string }> = {
  // linha do tempo
  "Fundação da": { en: "Founding of", es: "Fundación de" },
  "Campeão do": { en: "Champion of the", es: "Campeón del" },
  "Chegada de": { en: "Arrival of", es: "Llegada de" },
  "Despedida de": { en: "Farewell to", es: "Despedida de" },
  "do Top 20 do ano": { en: "in the year's Top 20", es: "del Top 20 del año" },
  "do": { en: "of the", es: "del" },
  "melhor técnico do ano": { en: "coach of the year", es: "mejor entrenador del año" },
  "Camisa de": { en: "Shirt of", es: "Camiseta de" },
  "aposentada": { en: "retired", es: "retirada" },
  "Linha do tempo da carreira": { en: "Career timeline", es: "Línea de tiempo de la carrera" },
  "A história começa no primeiro split": { en: "History starts with the first split", es: "La historia empieza en el primer split" },
  "Feche um split para ver a linha do tempo da carreira.": { en: "Finish a split to see the career timeline.", es: "Cierra un split para ver la línea de tiempo de la carrera." },
  // herói e seções
  "Legado e dinastia": { en: "Legacy and dynasty", es: "Legado y dinastía" },
  "temporadas": { en: "seasons", es: "temporadas" },
  "reputação": { en: "reputation", es: "reputación" },
  "Reputação": { en: "Reputation", es: "Reputación" },
  "Lendas": { en: "Legends", es: "Leyendas" },
  "Aproveitamento": { en: "Win rate", es: "Rendimiento" },
  "Cerimônia": { en: "Ceremony", es: "Ceremonia" },
  "Compartilhar": { en: "Share", es: "Compartir" },
  "Seções do legado": { en: "Legacy sections", es: "Secciones del legado" },
  "Prêmios da cena": { en: "Scene awards", es: "Premios de la escena" },
  "Recordes": { en: "Records", es: "Récords" },
  "Hall do manager": { en: "Manager hall", es: "Salón del mánager" },
  "Cards": { en: "Cards", es: "Cards" },
  // prêmios da cena
  "A primeira cerimônia sai no fim da temporada": { en: "The first ceremony comes at the end of the season", es: "La primera ceremonia llega al final de la temporada" },
  "A cada 4 splits a cena elege o Top 20 do ano, os MVPs dos eventos, a revelação, o melhor técnico e o time ideal, com base nos resultados e nas estatísticas da simulação.": { en: "Every 4 splits the scene picks the year's Top 20, the event MVPs, the breakthrough, the best coach and the team of the year, based on the simulation's results and stats.", es: "Cada 4 splits la escena elige el Top 20 del año, los MVP de los eventos, la revelación, el mejor entrenador y el equipo ideal, según los resultados y las estadísticas de la simulación." },
  "Rever cerimônia": { en: "Replay ceremony", es: "Volver a ver la ceremonia" },
  "Régua: nível (OVR) no fim do ano, rating HLTV 2.0 nos mapas simulados (com peso pela amostra) e títulos do time no circuito, com peso por tier, LAN e Major.": { en: "Criteria: level (OVR) at year end, HLTV 2.0 rating over simulated maps (weighted by sample) and team titles on the circuit, weighted by tier, LAN and Major.", es: "Criterio: nivel (OVR) al final del año, rating HLTV 2.0 en los mapas simulados (ponderado por la muestra) y títulos del equipo en el circuito, ponderados por tier, LAN y Major." },
  "Prêmios do ano": { en: "Awards of the year", es: "Premios del año" },
  "Jogador do ano": { en: "Player of the year", es: "Jugador del año" },
  "jogador do ano": { en: "player of the year", es: "jugador del año" },
  "JOGADOR DO ANO": { en: "PLAYER OF THE YEAR", es: "JUGADOR DEL AÑO" },
  "Revelação do ano": { en: "Breakthrough of the year", es: "Revelación del año" },
  "Melhor técnico": { en: "Best coach", es: "Mejor entrenador" },
  "Time ideal": { en: "Team of the year", es: "Equipo ideal" },
  "MVPs dos eventos": { en: "Event MVPs", es: "MVP de los eventos" },
  "Nenhum evento grande decidido nesta temporada.": { en: "No big event decided this season.", es: "Ningún evento grande decidido en esta temporada." },
  "Seu clube na cerimônia": { en: "Your club at the ceremony", es: "Tu club en la ceremonia" },
  // lendas
  "Camisas aposentadas": { en: "Retired shirts", es: "Camisetas retiradas" },
  "aposentada no split": { en: "retired in split", es: "retirada en el split" },
  "Lendas do clube": { en: "Club legends", es: "Leyendas del club" },
  "Nenhuma lenda ainda": { en: "No legends yet", es: "Ninguna leyenda aún" },
  "Títulos, Majors, longevidade, pico de nível e prêmios da cena fazem um jogador virar ídolo, lenda ou imortal do clube.": { en: "Titles, Majors, longevity, peak level and scene awards turn a player into a club idol, legend or immortal.", es: "Títulos, Majors, longevidad, pico de nivel y premios de la escena convierten a un jugador en ídolo, leyenda o inmortal del club." },
  "no elenco": { en: "in the squad", es: "en la plantilla" },
  "aposentado": { en: "retired", es: "retirado" },
  "Camisa aposentada": { en: "Shirt retired", es: "Camiseta retirada" },
  "Aposentar a camisa": { en: "Retire the shirt", es: "Retirar la camiseta" },
  "Aposentar a camisa de": { en: "Retire the shirt of", es: "¿Retirar la camiseta de" },
  "A camisa sobe para o teto do clube e entra na história da org para sempre. Não dá para desfazer.": { en: "The shirt goes up to the rafters and into the org's history forever. This can't be undone.", es: "La camiseta sube al techo del club y entra en la historia de la org para siempre. No se puede deshacer." },
  "Camisa: só para lendas e imortais": { en: "Shirt: legends and immortals only", es: "Camiseta: solo leyendas e inmortales" },
  "Camisa: depois que ele sair ou parar": { en: "Shirt: once he leaves or retires", es: "Camiseta: cuando se vaya o se retire" },
  "Ídolo": { en: "Idol", es: "Ídolo" },
  "Lenda": { en: "Legend", es: "Leyenda" },
  "Imortal": { en: "Immortal", es: "Inmortal" },
  // recordes
  "Período": { en: "Period", es: "Período" },
  "Recordes do clube": { en: "Club records", es: "Récords del club" },
  "Recordes individuais": { en: "Individual records", es: "Récords individuales" },
  "Sem recordes ainda.": { en: "No records yet.", es: "Sin récords aún." },
  "Números all-time no clube": { en: "All-time numbers at the club", es: "Números históricos en el club" },
  "Melhor Major": { en: "Best Major", es: "Mejor Major" },
  "Majors vencidos": { en: "Majors won", es: "Majors ganados" },
  "Títulos seguidos": { en: "Titles in a row", es: "Títulos seguidos" },
  "títulos seguidos": { en: "titles in a row", es: "títulos seguidos" },
  "Splits seguidos no top 4": { en: "Splits in a row in the top 4", es: "Splits seguidos en el top 4" },
  "Mais vitórias num split": { en: "Most wins in a split", es: "Más victorias en un split" },
  "Maior premiação num split": { en: "Biggest prize in a split", es: "Mayor premio en un split" },
  "Campanha invicta": { en: "Unbeaten run", es: "Campaña invicta" },
  "Mais mapas pelo clube": { en: "Most maps for the club", es: "Más mapas por el club" },
  "Mais abates pelo clube": { en: "Most kills for the club", es: "Más bajas por el club" },
  "Maior rating (20+ mapas)": { en: "Best rating (20+ maps)", es: "Mejor rating (20+ mapas)" },
  "Maior rating num evento": { en: "Best rating in an event", es: "Mejor rating en un evento" },
  "Mais títulos": { en: "Most titles", es: "Más títulos" },
  "Maior OVR": { en: "Highest OVR", es: "Mayor OVR" },
  "Mais splits no clube": { en: "Most splits at the club", es: "Más splits en el club" },
  "Mais mapas": { en: "Most maps", es: "Más mapas" },
  "Maior rating": { en: "Best rating", es: "Mejor rating" },
  // Hall do manager
  "Hall da Fama do manager": { en: "Manager Hall of Fame", es: "Salón de la Fama del mánager" },
  "Comum": { en: "Common", es: "Común" },
  "Rara": { en: "Rare", es: "Rara" },
  "Épica": { en: "Epic", es: "Épica" },
  "Lendária": { en: "Legendary", es: "Legendaria" },
  "Elite": { en: "Elite", es: "Élite" },
  "Top regional": { en: "Regional top", es: "Top regional" },
  "Mediano": { en: "Average", es: "Mediano" },
  "Iniciante": { en: "Beginner", es: "Principiante" },
  "Primeira taça": { en: "First trophy", es: "Primera copa" },
  "Vença um campeonato": { en: "Win a tournament", es: "Gana un campeonato" },
  "Estreia no Major": { en: "Major debut", es: "Debut en el Major" },
  "Dispute um Major": { en: "Play a Major", es: "Juega un Major" },
  "Colecionador": { en: "Collector", es: "Coleccionista" },
  "Vença 5 campeonatos": { en: "Win 5 tournaments", es: "Gana 5 campeonatos" },
  "Final de Major": { en: "Major final", es: "Final de Major" },
  "Chegue a uma final de Major": { en: "Reach a Major final", es: "Llega a una final de Major" },
  "Invicto": { en: "Unbeaten", es: "Invicto" },
  "Feche um split com 5+ vitórias e nenhuma derrota": { en: "Finish a split with 5+ wins and no losses", es: "Cierra un split con 5+ victorias y ninguna derrota" },
  "Elite mundial": { en: "World elite", es: "Élite mundial" },
  "Seja campeão jogando no tier 1": { en: "Win a title playing in tier 1", es: "Sé campeón jugando en el tier 1" },
  "Fábrica de craques": { en: "Star factory", es: "Fábrica de cracks" },
  "Coloque 3 jogadores no Top 20 do ano": { en: "Put 3 players in the year's Top 20", es: "Mete 3 jugadores en el Top 20 del año" },
  "Vença um Major": { en: "Win a Major", es: "Gana un Major" },
  "Dinastia": { en: "Dynasty", es: "Dinastía" },
  "Vença 3 splits seguidos": { en: "Win 3 splits in a row", es: "Gana 3 splits seguidos" },
  "Técnico do ano": { en: "Coach of the year", es: "Entrenador del año" },
  "Ganhe o prêmio de melhor técnico da cena": { en: "Win the scene's best coach award", es: "Gana el premio a mejor entrenador de la escena" },
  "Casa de lendas": { en: "House of legends", es: "Casa de leyendas" },
  "Tenha 3 lendas do clube": { en: "Have 3 club legends", es: "Ten 3 leyendas del club" },
  "Dono do mundo": { en: "Owner of the world", es: "Dueño del mundo" },
  "Tenha o #1 do Top 20 do ano": { en: "Have the #1 of the year's Top 20", es: "Ten al #1 del Top 20 del año" },
  "Tricampeão": { en: "Three-time champion", es: "Tricampeón" },
  "Vença 3 Majors": { en: "Win 3 Majors", es: "Gana 3 Majors" },
  "Uma década": { en: "A decade", es: "Una década" },
  "Complete 40 splits na carreira": { en: "Complete 40 splits in your career", es: "Completa 40 splits en la carrera" },
  // cards
  "de circuito": { en: "circuit", es: "de circuito" },
  "Minha dinastia": { en: "My dynasty", es: "Mi dinastía" },
  "Vença um Major para liberar este card.": { en: "Win a Major to unlock this card.", es: "Gana un Major para desbloquear esta card." },
  "Tenha o #1 do Top 20 do ano para liberar este card.": { en: "Have the #1 of the year's Top 20 to unlock this card.", es: "Ten al #1 del Top 20 del año para desbloquear esta card." },
  "Card compartilhado.": { en: "Card shared.", es: "Card compartida." },
  "Card baixado e texto copiado.": { en: "Card downloaded and text copied.", es: "Card descargada y texto copiado." },
  "Gerando…": { en: "Generating…", es: "Generando…" },
  "Gerar o card": { en: "Generate the card", es: "Generar la card" },
  "Baixar PNG": { en: "Download PNG", es: "Descargar PNG" },
  "O card é gerado no seu aparelho (PNG 1080×1350). No celular, abre o compartilhamento do sistema; no computador, baixa a imagem e copia o texto.": { en: "The card is generated on your device (PNG 1080×1350). On mobile it opens the system share sheet; on desktop it downloads the image and copies the text.", es: "La card se genera en tu dispositivo (PNG 1080×1350). En el móvil abre el menú de compartir; en el ordenador descarga la imagen y copia el texto." },
  "Card bloqueado": { en: "Card locked", es: "Card bloqueada" },
  "Compartilhar o card": { en: "Share the card", es: "Compartir la card" },
  "Construa a sua dinastia no Road to Major": { en: "Build your dynasty in Road to Major", es: "Construye tu dinastía en Road to Major" },
  "Sala de troféus": { en: "Trophy room", es: "Sala de trofeos" },
  "A primeira taça está a caminho": { en: "The first trophy is on its way", es: "La primera copa está en camino" },
  "As lendas ainda estão sendo escritas": { en: "The legends are still being written", es: "Las leyendas aún se están escribiendo" },
  "Os campeões": { en: "The champions", es: "Los campeones" },
  "no Road to Major": { en: "in Road to Major", es: "en Road to Major" },
  "é campeã do Major no Road to Major": { en: "are Major champions in Road to Major", es: "es campeona del Major en Road to Major" },
  "Minha dinastia no Road to Major": { en: "My dynasty in Road to Major", es: "Mi dinastía en Road to Major" },
  // cerimônia
  "Os 20 melhores jogadores do ano": { en: "The 20 best players of the year", es: "Los 20 mejores jugadores del año" },
  "Escolhidos pelos resultados e pelas estatísticas da temporada simulada. Depois: revelação, melhor técnico, MVPs e o time ideal.": { en: "Picked by the results and stats of the simulated season. Then: breakthrough, best coach, MVPs and the team of the year.", es: "Elegidos por los resultados y las estadísticas de la temporada simulada. Después: revelación, mejor entrenador, MVP y el equipo ideal." },
  "Começar a cerimônia": { en: "Start the ceremony", es: "Empezar la ceremonia" },
  "Cerimônia da cena": { en: "Scene ceremony", es: "Ceremonia de la escena" },
};
