// Dicionario de traducao do modo carreira (chave = string PT normalizada -> EN/ES).
// ct('PT') faz o lookup; string sem entrada cai no PT (nunca quebra).
export const CAREER_STR: Record<string, { en: string; es: string }> = {
  'Atributos': { en: 'Attributes', es: 'Atributos' },
  'Campanha encerrada': { en: 'Campaign complete', es: 'Campaña finalizada' },
  'CLÁSSICO': { en: 'RIVALRY', es: 'CLÁSICO' },
  'A sequência de partidas pesou. Use carga reduzida ou invista em psicologia para recuperar o elenco.': { en: 'The run of matches took its toll. Use reduced load or invest in psychology to recover the roster.', es: 'La seguidilla de partidos pasó factura. Usa carga reducida o invierte en psicología para recuperar la plantilla.' },
  'Aplicar carga reduzida na próxima série': { en: 'Apply reduced load for the next series', es: 'Aplicar carga reducida en la próxima serie' },
  'Fadiga': { en: 'Fatigue', es: 'Fatiga' },
  'Fadiga:': { en: 'Fatigue:', es: 'Fatiga:' },
  'Remover carga reduzida': { en: 'Remove reduced load', es: 'Quitar carga reducida' },
  'Risco de burnout:': { en: 'Burnout risk:', es: 'Riesgo de burnout:' },
  'carga reduzida': { en: 'reduced load', es: 'carga reducida' },
  '🛌 Carga reduzida ativa': { en: '🛌 Reduced load active', es: '🛌 Carga reducida activa' },
  '🛌 Dar carga reduzida': { en: '🛌 Set reduced load', es: '🛌 Dar carga reducida' },
  'Os confrontos repetidos e equilibrados transformaram esta série numa rivalidade. O elenco entra mais focado nos próximos encontros.': { en: 'Repeated, close matchups turned this series into a rivalry. The roster enters future meetings with extra focus.', es: 'Los enfrentamientos repetidos y parejos convirtieron esta serie en una rivalidad. La plantilla afronta los próximos duelos con más concentración.' },
  'Rivalidade nível': { en: 'Rivalry level', es: 'Nivel de rivalidad' },
  'Virou clássico:': { en: 'A rivalry is born:', es: 'Nace un clásico:' },
  'foco': { en: 'focus', es: 'concentración' },
  'Campanha registrada no Hall da Fama com elenco, MVP e recordes.': { en: 'Campaign saved to the Hall of Fame with roster, MVP and records.', es: 'Campaña guardada en el Salón de la Fama con plantilla, MVP y récords.' },
  'Hall indisponível agora. O registro será tentado novamente ao reabrir este resultado.': { en: 'The Hall is unavailable now. Registration will be retried when this result is reopened.', es: 'El Salón no está disponible ahora. El registro se reintentará al reabrir este resultado.' },
  'Registrando a campanha no Hall da Fama…': { en: 'Saving the campaign to the Hall of Fame…', es: 'Guardando la campaña en el Salón de la Fama…' },
  'Seu caminho restante': { en: 'Your remaining path', es: 'Tu camino restante' },
  'Stages decididos antes da sua entrada': { en: 'Stages decided before your entry', es: 'Stages decididos antes de tu entrada' },
  'Você entrou direto no': { en: 'You entered directly in', es: 'Entraste directamente en' },
  'agora': { en: 'now', es: 'ahora' },
  'auto-simulado': { en: 'auto-simulated', es: 'auto-simulado' },
  'classificados': { en: 'qualified', es: 'clasificados' },
  'pela frente': { en: 'ahead', es: 'por delante' },
  'Caixa pra acordos': { en: 'Deal budget', es: 'Caja para acuerdos' },
  'Caminho até o título': { en: 'Path to the title', es: 'Camino al título' },
  'Cinco titular': { en: 'Starting five', es: 'Cinco titular' },
  'Classificar ao mata-mata': { en: 'Reach the playoffs', es: 'Clasificar a playoffs' },
  'Em volta do circuito': { en: 'Around the circuit', es: 'Alrededor del circuito' },
  'Entrosamento': { en: 'Familiarity', es: 'Entendimiento' },
  'Erguer o título do split': { en: 'Win the split title', es: 'Ganar el título del split' },
  'Funções AWP+IGL': { en: 'AWP+IGL roles', es: 'Roles AWP+IGL' },
  'Fãs': { en: 'Fans', es: 'Aficionados' },
  'HLTV Top 20': { en: 'HLTV Top 20', es: 'Top 20 HLTV' },
  'Histórico da carreira': { en: 'Career history', es: 'Historial de carrera' },
  'Janela aberta · feche acordos pra próxima temporada': { en: 'Window open · close deals for next season', es: 'Mercado abierto · cierra acuerdos para la próxima temporada' },
  'Jogar': { en: 'Play', es: 'Jugar' },
  'Melhores do': { en: 'Best of', es: 'Mejores de' },
  'Modos': { en: 'Modes', es: 'Modos' },
  'Moral média': { en: 'Average morale', es: 'Moral media' },
  'Objetivo da diretoria': { en: 'Board objective', es: 'Objetivo de la directiva' },
  'Objetivos': { en: 'Objectives', es: 'Objetivos' },
  'Partidas': { en: 'Matches', es: 'Partidos' },
  'Próximo jogo': { en: 'Next match', es: 'Próximo partido' },
  'Química do elenco': { en: 'Squad chemistry', es: 'Química de la plantilla' },
  'Sem resultados ainda.': { en: 'No results yet.', es: 'Sin resultados todavía.' },
  'Simular': { en: 'Simulate', es: 'Simular' },
  'Split inteiro': { en: 'Full split', es: 'Split completo' },
  'Sua organização': { en: 'Your organization', es: 'Tu organización' },
  'Times no circuito': { en: 'Circuit teams', es: 'Equipos del circuito' },
  'Título': { en: 'Title', es: 'Título' },
  'Vencer uma série MD3': { en: 'Win a Bo3 series', es: 'Ganar una serie MD3' },
  'Ver tudo': { en: 'See all', es: 'Ver todo' },
  'Voltar ao menu': { en: 'Back to menu', es: 'Volver al menú' },
  'força': { en: 'strength', es: 'fuerza' },
  'prestígio': { en: 'prestige', es: 'prestigio' },
  'Seu cinco titular': { en: 'Your starting five', es: 'Tu quinteto titular' },
  'Gerenciar elenco →': { en: 'Manage squad →', es: 'Gestionar plantilla →' },
  'Gestão do elenco': { en: 'Squad management', es: 'Gestión de la plantilla' },
  'OVR médio do elenco': { en: 'Squad average OVR', es: 'OVR promedio de la plantilla' },
  'Posição na tabela': { en: 'Standing', es: 'Posición en la tabla' },
  'Carreira': { en: 'Career', es: 'Carrera' },
  'título': { en: 'title', es: 'título' },
  'Semifinal': { en: 'Semifinal', es: 'Semifinal' },
  'Final': { en: 'Final', es: 'Final' },
  'Fase suíça': { en: 'Swiss stage', es: 'Fase suiza' },
  'Playoffs': { en: 'Playoffs', es: 'Playoffs' },
  'Mata-mata MD3': { en: 'Playoffs Bo3', es: 'Playoffs MD3' },
  'Clique numa série encerrada para ver as estatísticas': { en: 'Click a finished series to see the stats', es: 'Haz clic en una serie terminada para ver las estadísticas' },
  'Estatísticas da partida': { en: 'Match stats', es: 'Estadísticas del partido' },
  'Ambos os lados': { en: 'Both sides', es: 'Ambos lados' },
  'Terrorista (TR)': { en: 'Terrorist (T)', es: 'Terrorista (TR)' },
  'Counter-Terrorist (CT)': { en: 'Counter-Terrorist (CT)', es: 'Counter-Terrorist (CT)' },
  'Ambos': { en: 'Both', es: 'Ambos' },
  'Todos os mapas': { en: 'All maps', es: 'Todos los mapas' },
  'Kills - Assistências - Mortes': { en: 'Kills - Assists - Deaths', es: 'Bajas - Asistencias - Muertes' },
  'Rounds com 2+ abates (multi-kills)': { en: 'Rounds with 2+ kills (multi-kills)', es: 'Rondas con 2+ bajas (multi-kills)' },
  'Kill / Assist / Survive / Trade': { en: 'Kill / Assist / Survive / Trade', es: 'Baja / Asistencia / Sobrevivir / Intercambio' },
  'Clutches (1vX) vencidos': { en: 'Clutches (1vX) won', es: 'Clutches (1vX) ganados' },
  'Abates (de headshot)': { en: 'Kills (headshots)', es: 'Bajas (headshots)' },
  'Mortes (trocadas)': { en: 'Deaths (traded)', es: 'Muertes (intercambiadas)' },
  'Destaque da partida': { en: 'Player of the match', es: 'Jugador del partido' },
  'AWPer dedicado segurando os lados': { en: 'Dedicated AWPer holding the angles', es: 'AWPer dedicado aguantando los lados' },
  'SEM AWPER: CT vira sofrimento': { en: 'NO AWPER: CT side is a struggle', es: 'SIN AWPER: el lado CT sufre' },
  'IGL no comando das rondas': { en: 'IGL calling the rounds', es: 'IGL al mando de las rondas' },
  'SEM IGL: sem leitura tatica em rounds fechados': { en: 'NO IGL: no tactical read in tight rounds', es: 'SIN IGL: sin lectura táctica en rondas cerradas' },
  'AWPers demais brigando pela arma': { en: 'Too many AWPers fighting for the rifle', es: 'Demasiados AWPers peleando por el arma' },
  'Dois AWPers principais dividem o orcamento': { en: 'Two main AWPers split the buy', es: 'Dos AWPers principales dividen el presupuesto' },
  'Vozes de comando em conflito': { en: 'Conflicting in-game leaders', es: 'Voces de mando en conflicto' },
  'Entry fragger abrindo espaco': { en: 'Entry fragger opening space', es: 'Entry fragger abriendo espacio' },
  'Suporte/lurker fechando o mapa': { en: 'Support/lurker locking down the map', es: 'Apoyo/lurker cerrando el mapa' },
  'Composicao completa: cinco funcoes distintas': { en: 'Full composition: five distinct roles', es: 'Composición completa: cinco roles distintos' },
  'Quimica de era entre os jogadores': { en: 'Era chemistry between players', es: 'Química de era entre los jugadores' },
  'jogadores do mesmo pais aceleram a comunicacao': { en: 'players from the same country speed up comms', es: 'jugadores del mismo país aceleran la comunicación' },
  'Linha do tempo': { en: 'Timeline', es: 'Línea de tiempo' },
  'Neste split': { en: 'This split', es: 'En este split' },
  'Grupos': { en: 'Groups', es: 'Grupos' },
  'Nacionalidade do core': { en: 'Core nationality', es: 'Nacionalidad del core' },
  'Prestígio da org (cresce com títulos, Major, tier e VRS; atrai patrocínio)': { en: 'Org prestige (grows with titles, Major, tier and VRS; attracts sponsors)', es: 'Prestigio de la org (crece con títulos, Major, tier y VRS; atrae patrocinio)' },
  'Resolve todas as rodadas restantes de uma vez e vai pro mata-mata': { en: 'Resolve all remaining rounds at once and go to playoffs', es: 'Resuelve todas las rondas restantes de una vez y pasa a playoffs' },
  'Ver perfil do jogador': { en: 'View player profile', es: 'Ver perfil del jugador' },
  'Definir a função deste jogador': { en: 'Set this player\'s role', es: 'Definir el rol de este jugador' },
  'Maior OVR já alcançado': { en: 'Highest OVR reached', es: 'Mayor OVR alcanzado' },
  '- confrontos': { en: '- matchups', es: '- enfrentamientos' },
  'Rodada de abertura': { en: 'Opening round', es: 'Ronda de apertura' },
  'Vencedores + Eliminação': { en: 'Winners + Elimination', es: 'Ganadores + Eliminación' },
  'Decisão': { en: 'Decider', es: 'Decisión' },
  '! Você venceu no seu nível e subiu de tier.': { en: '! You won at your level and moved up a tier.', es: '! Ganaste en tu nivel y subiste de tier.' },
  '" (bônus': { en: '" (bonus', es: '" (bono' },
  '% confiança': { en: '% confidence', es: '% confianza' },
  '(2 grupos de 4, dupla eliminação: abertura → vencedores/eliminação → decisão; abertura é MD1, o resto MD3) → os': { en: '(2 groups of 4, double elimination: opening → winners/elimination → decider; opening is MD1, the rest MD3) → the', es: '(2 grupos de 4, doble eliminación: apertura → ganadores/eliminación → decisión; la apertura es MD1, el resto MD3) → los' },
  '(atual)': { en: '(current)', es: '(actual)' },
  '(bônus': { en: '(bonus', es: '(bono' },
  '(cresce mais rápido a cada split rumo ao seu': { en: '(grows faster each split toward your', es: '(crece más rápido cada split rumbo a tu' },
  '(fase de grupos + mata-mata) que vale prêmio e': { en: '(group stage + playoffs) worth prize money and', es: '(fase de grupos + playoffs) que vale premio y' },
  '(força': { en: '(strength', es: '(fuerza' },
  '(org de elite) ofereceu': { en: '(elite org) offered', es: '(org de elite) ofreció' },
  '(semis MD3 + final MD5). É o formato real do CS (IEM/BLAST/Major), não liga de pontos.': { en: '(semis MD3 + final MD5). It\'s the real CS format (IEM/BLAST/Major), not a points league.', es: '(semis MD3 + final MD5). Es el formato real del CS (IEM/BLAST/Major), no una liga de puntos.' },
  '(só elencos CS2). Você começa com': { en: '(CS2 rosters only). You start with', es: '(solo rosters CS2). Empiezas con' },
  '(top {MAJOR_VRS_CUT} garantem vaga). Hora de enfrentar os melhores do mundo.': { en: '(top {MAJOR_VRS_CUT} guarantee spots). Time to face the best in the world.', es: '(los mejores {MAJOR_VRS_CUT} garantizan plaza). Hora de enfrentar a los mejores del mundo.' },
  '(você': { en: '(you', es: '(tú' },
  '(você está em': { en: '(you\'re in', es: '(estás en' },
  '(você está em #': { en: '(you\'re in #', es: '(estás en #' },
  ') está em outro nível nesse split. Provavelmente o melhor do mundo agora. 🔥': { en: ') is on another level this split. Probably the best in the world right now. 🔥', es: ') está en otro nivel este split. Probablemente el mejor del mundo ahora. 🔥' },
  '). Decida na janela de transferências.': { en: '). Decide in the transfer window.', es: '). Decide en la ventana de transferencias.' },
  '+ troca': { en: '+ swap', es: '+ intercambio' },
  '+ troca:': { en: '+ swap:', es: '+ intercambio:' },
  ', mas você compete na': { en: ', but you compete in the', es: ', pero compites en la' },
  ', terminar no fundo te': { en: ', finishing at the bottom', es: ', terminar en el fondo te' },
  '. Ganhe VRS vencendo partidas, indo longe e levando campeonatos (próximo Major: Split': { en: '. Earn VRS by winning matches, going deep and lifting titles (next Major: Split', es: '. Gana VRS ganando partidos, llegando lejos y llevándote títulos (próximo Major: Split' },
  '. Pré-jogo: confira o relatório do adversário na Visão geral antes de cada partida.': { en: '. Pre-game: check the opponent report in the Overview before every match.', es: '. Pre-partido: revisa el informe del rival en la Vista general antes de cada partido.' },
  '. Quanto maior, mais o esquema pesa na partida — pro bem e pro mal, conforme o contexto.': { en: '. The higher it is, the more the scheme weighs on the match — for better or worse, depending on context.', es: '. Cuanto más alto, más pesa el esquema en el partido — para bien y para mal, según el contexto.' },
  '. Só o': { en: '. Only the', es: '. Solo el' },
  '. Terminou no fundo da tabela; recupere o nível no próximo split.': { en: '. You finished at the bottom of the table; get your level back next split.', es: '. Terminaste en el fondo de la tabla; recupera el nivel el próximo split.' },
  '. Você entrou no': { en: '. You entered the', es: '. Entraste en el' },
  '. Você joga no seu tier ou abaixo; vencer o seu circuito te': { en: '. You play in your tier or below; winning your circuit', es: '. Juegas en tu tier o por debajo; ganar tu circuito te' },
  '1 contrato vence': { en: '1 contract expires', es: '1 contrato vence' },
  '5 jogadores': { en: '5 players', es: '5 jugadores' },
  ': \'\'}. A cena segue fervendo enquanto você disputa a sua região.': { en: ': \'\'}. The scene keeps boiling while you battle for your region.', es: ': \'\'}. La escena sigue hirviendo mientras peleas por tu región.' },
  ': circuito de acesso, times em ascensão. Grupos + playoffs. Onde toda org começa.': { en: ': entry circuit, rising teams. Groups + playoffs. Where every org begins.', es: ': circuito de acceso, equipos en ascenso. Grupos + playoffs. Donde toda org empieza.' },
  ': durante o split é com o elenco que você tem.': { en: ': during the split you ride with the roster you\'ve got.', es: ': durante el split juegas con el roster que tienes.' },
  ': fase de grupos (GSL, dupla eliminação) + playoffs com a elite do ranking. Principal caminho de pontos pro Major; paga muito.': { en: ': group stage (GSL, double elimination) + playoffs with the ranking elite. Main points path to the Major; pays big.', es: ': fase de grupos (GSL, doble eliminación) + playoffs con la élite del ranking. Principal camino de puntos al Major; paga mucho.' },
  ': jogador em ascensão melhora, veterano em declínio cai; valor e salário acompanham. Olhe a fase de carreira antes de contratar.': { en: ': a rising player improves, a declining veteran drops; value and wage follow. Check the career stage before signing.', es: ': un jugador en ascenso mejora, un veterano en declive cae; valor y salario lo acompañan. Mira la fase de carrera antes de contratar.' },
  ': o segundo escalão do ranking (Astralis, paiN, FaZe, MIBR, TYLOO e cia), grupos GSL + playoffs. Vença pra subir ao Tier 1 e brigar pelo Major.': { en: ': the second tier of the ranking (Astralis, paiN, FaZe, MIBR, TYLOO and co.), GSL groups + playoffs. Win to climb to Tier 1 and fight for the Major.', es: ': el segundo escalón del ranking (Astralis, paiN, FaZe, MIBR, TYLOO y compañía), grupos GSL + playoffs. Gana para subir al Tier 1 y pelear por el Major.' },
  ': vice-campeão (perdeu a final)': { en: ': runner-up (lost the final)', es: ': subcampeón (perdió la final)' },
  ': vão os': { en: ': go the', es: ': van los' },
  '; o próximo é no fim do': { en: '; the next one is at the end of', es: '; el próximo es al final de' },
  'A': { en: 'The', es: 'La' },
  'A Astralis foi a maior dinastia do CS, mas hoje briga no meio do pelotão. Reconstrua o império dinamarquês.': { en: 'Astralis was the greatest CS dynasty, but today fights in the middle of the pack. Rebuild the Danish empire.', es: 'Astralis fue la mayor dinastía de CS, pero hoy lucha en el medio del pelotón. Reconstruye el imperio danés.' },
  'A BIG carrega o CS alemão nas costas, mas precisa voltar à elite. Reerga o projeto.': { en: 'BIG carries German CS on its back but needs to return to the elite. Revive the project.', es: 'BIG carga el CS alemán a sus espaldas pero necesita volver a la élite. Revive el proyecto.' },
  'A FURIA é a bandeira do CS brasileiro no mundo. A cobrança é alta: top 4 mundial e presença no Major.': { en: 'FURIA is the flag of Brazilian CS worldwide. The pressure is high: top 4 and Major presence.', es: 'FURIA es la bandera del CS brasileño en el mundo. La presión es alta: top 4 mundial y presencia en el Major.' },
  'A FaZe despencou pro #22 do mundo no pós-karrigan. Pegue o projeto americano em obras e devolva a org à elite mundial.': { en: 'FaZe plummeted to #22 in the world post-karrigan. Take over the American project and return the org to the elite.', es: 'FaZe se desplomó al #22 del mundo post-karrigan. Toma el proyecto estadounidense en construcción y devuelve la org a la élite.' },
  'A MOUZ aposta numa base jovem e promissora. Lapide os talentos e brigue pelo topo mundial.': { en: 'MOUZ bets on a young and promising core. Develop the talent and fight for the world top.', es: 'MOUZ apuesta por una base joven y prometedora. Desarrolla el talento y lucha por la cima mundial.' },
  'A NA quer voltar a brigar lá em cima. Construa o projeto e dispute o Major mundial.': { en: 'NA wants to fight at the top again. Build the project and compete for the world Major.', es: 'NA quiere volver a luchar en la cima. Construye el proyecto y compite por el Major mundial.' },
  'A NAVI vive de glórias passadas. Coloque a lenda da CIS de volta na elite mundial.': { en: 'NAVI lives off past glories. Put the CIS legend back in the world elite.', es: 'NAVI vive de glorias pasadas. Pon la leyenda de la CIS de vuelta en la élite mundial.' },
  'A SAW é a esperança lusa, mas começa lá embaixo no ranking. Leve Portugal, do zero, até o Major mundial.': { en: 'SAW is Portugal\'s hope, but starts low in the ranking. Take Portugal from zero to the world Major.', es: 'SAW es la esperanza portuguesa, pero comienza baja en el ranking. Lleva a Portugal de cero al Major mundial.' },
  'A bandeira do time passa a ser a dessa região.': { en: 'The team\'s flag will become that region\'s.', es: 'La bandera del equipo pasará a ser la de esa región.' },
  'A cada split você entra num circuito. O Tier 3 é o acesso (onde toda org começa) e o Tier 1 é a elite mundial. Vencer promove; só o Tier 1 dá vaga no Major.': { en: 'Each split you enter a circuit. Tier 3 is the entry level (where every org starts) and Tier 1 is world elite. Winning promotes you; only Tier 1 earns a Major slot.', es: 'Cada split ingresas a un circuito. Tier 3 es el acceso (donde toda org comienza) y Tier 1 es la élite mundial. Ganar te asciende; solo Tier 1 da plaza en el Major.' },
  'A campanha mundial terminou em': { en: 'The world campaign ended in', es: 'La campaña mundial terminó en' },
  'A comissão técnica destaca a evolução de': { en: 'The coaching staff highlights the growth of', es: 'El cuerpo técnico destaca la evolución de' },
  'A confiança caiu — atenção redobrada no próximo split.': { en: 'Confidence dropped — extra focus needed next split.', es: 'La confianza cayó — se necesita más enfoque en el próximo split.' },
  'A confiança subiu.': { en: 'Confidence went up.', es: 'La confianza subió.' },
  'A diretoria da': { en: 'The board of', es: 'La directiva de' },
  'A diretoria da {save.org?.name} te demitiu': { en: 'The board of {save.org?.name} fired you', es: 'La junta de {save.org?.name} te despidió' },
  'A paiN carrega mais de uma década de torcida brasileira. Devolva os títulos pra casa.': { en: 'paiN carries over a decade of Brazilian support. Return the titles home.', es: 'paiN lleva más de una década de apoyo brasileño. Devuelve los títulos a casa.' },
  'A premiação entra conforme sua colocação. O "saldo fixo" é patrocínio − folha (antes do prêmio); se ficar negativo, você queima caixa todo split.': { en: 'Prize money comes in based on your placement. The "fixed balance" is sponsorship − payroll (before prize money); if it goes negative, you burn cash every split.', es: 'El premio entra según tu colocación. El "saldo fijo" es patrocinio − nómina (antes del premio); si queda negativo, quemas caja cada split.' },
  'A sigla mais histórica do Brasil quer voltar a brigar lá em cima. Construa do circuito até o Major.': { en: 'Brazil\'s most historic org wants to fight at the top again. Build from circuit to Major.', es: 'La org más histórica de Brasil quiere volver a luchar en la cima. Construye desde el circuito hasta el Major.' },
  'A vaga no Major é dos top {MAJOR_VRS_CUT} do ranking VRS mundial (você está em #{worldRank}). Ganhe VRS vencendo partidas, indo longe e levando campeonatos pra subir no ranking. Major a cada {MAJOR_EVERY} splits (próximo: Split {majorNow ? save.split : nextMajorSplit}).': { en: 'The Major spot goes to the top {MAJOR_VRS_CUT} in the global VRS ranking (you\'re at #{worldRank}). Earn VRS by winning matches, going deep, and winning tournaments to climb the ranking. Major every {MAJOR_EVERY} splits (next: Split {majorNow ? save.split : nextMajorSplit}).', es: 'La plaza del Major es para el top {MAJOR_VRS_CUT} del ranking VRS mundial (estás en #{worldRank}). Gana VRS ganando partidas, llegando lejos y ganando campeonatos para subir en el ranking. Major cada {MAJOR_EVERY} splits (próximo: Split {majorNow ? save.split : nextMajorSplit}).' },
  'Abertura · MD1': { en: 'Opening · MD1', es: 'Apertura · MD1' },
  'Abrir Finanças →': { en: 'Open Finances →', es: 'Abrir Finanzas →' },
  'Abrir →': { en: 'Open →', es: 'Abrir →' },
  'Academia': { en: 'Academy', es: 'Academia' },
  'Academia cheia': { en: 'Academy full', es: 'Academia llena' },
  'Academia ·': { en: 'Academy ·', es: 'Academia ·' },
  'Aceitar': { en: 'Accept', es: 'Aceptar' },
  'Aceitar vende o jogador na próxima janela (a grana entra no caixa). O jogador continua jogando até lá.': { en: 'Accept sells the player next window (money enters cash). Player continues playing until then.', es: 'Aceptar vende al jugador en la próxima ventana (el dinero entra en caja). El jugador sigue jugando hasta entonces.' },
  'Acordos fechados': { en: 'Closed deals', es: 'Acuerdos cerrados' },
  'Acordos fechados na temporada passada entraram em vigor:': { en: 'Deals closed last season took effect:', es: 'Los acuerdos cerrados la temporada pasada entraron en vigor:' },
  'Agressivo': { en: 'Aggressive', es: 'Agresivo' },
  'Ao assinar você se compromete por X splits (não dá pra rescindir antes). Marcas maiores pedem mais VRS e contratos mais longos.': { en: 'Signing commits you for X splits (can\'t terminate early). Bigger brands demand higher VRS and longer deals.', es: 'Al firmar se compromete por X splits (no se puede rescindir antes). Las marcas más grandes exigen VRS más alto y acuerdos más largos.' },
  'Apagar tudo e recomeçar do zero': { en: 'Wipe everything and start from scratch', es: 'Borrar todo y empezar de cero' },
  'Aprov.': { en: 'Win %', es: 'Aprv.' },
  'As estatísticas de carreira aparecem aqui depois de jogar o primeiro split. Elas sobem conforme os jogadores evoluem.': { en: 'Career stats show up here after you play the first split. They rise as the players develop.', es: 'Las estadísticas de carrera aparecen aquí después de jugar el primer split. Suben a medida que los jugadores evolucionan.' },
  'Assuma uma org com contexto e metas: FaZe em reconstrução, lendas como a MIBR 2006, a SAW de Portugal e mais.': { en: 'Take over an org with context and goals: FaZe rebuilding, legends like MIBR 2006, Portugal\'s SAW and more.', es: 'Toma una org con contexto y objetivos: FaZe en reconstrucción, leyendas como MIBR 2006, SAW de Portugal y más.' },
  'Assuma uma organização (modo carreira)': { en: 'Take over an organization (career mode)', es: 'Toma una organización (modo carrera)' },
  'Assuma uma organização com': { en: 'Take over an organization with', es: 'Toma una organización con' },
  'Assumir org com elenco (tier baixo/médio)': { en: 'Take over org with roster (low/mid tier)', es: 'Toma una org con plantilla (tier bajo/medio)' },
  'Astralis: reviver a dinastia': { en: 'Astralis: reviving the dynasty', es: 'Astralis: reviviendo la dinastía' },
  'BIG: a esperança alemã': { en: 'BIG: German hope', es: 'BIG: la esperanza alemana' },
  'Baixa': { en: 'Low', es: 'Baja' },
  'Bem-vindo ao Modo Carreira': { en: 'Welcome to Career Mode', es: 'Bienvenido al Modo Carrera' },
  'Boa sorte na estrada até o Major. Dá pra rever este guia quando quiser no botão ❔ lá no topo. Bora.': { en: 'Good luck on the road to the Major. You can review this guide anytime using the ❔ button at the top. Let\'s go.', es: 'Buena suerte en el camino al Major. Puedes revisar esta guía en cualquier momento usando el botón ❔ arriba. Vamos.' },
  'Buscar jogador ou time…': { en: 'Search player or team…', es: 'Buscar jugador o equipo…' },
  'Buscar jogador…': { en: 'Search player…', es: 'Buscar jugador…' },
  'CAIXA': { en: 'CASH', es: 'CAJA' },
  'CAMPEÃO DO MAJOR': { en: 'MAJOR CHAMPION', es: 'CAMPEÓN DEL MAJOR' },
  'CAMPEÃO e a TL surtou': { en: 'CHAMPION and TL lost it', es: 'CAMPEÓN y TL se descontroló' },
  'CLASSIFICADO PRO MAJOR MUNDIAL!': { en: 'QUALIFIED FOR THE WORLD MAJOR!', es: '¡CLASIFICADO AL MAJOR MUNDIAL!' },
  'CLASSIFICADO PRO MAJOR MUNDIAL! Você está em #{worldRank} no ranking VRS mundial': { en: 'QUALIFIED FOR THE WORLD MAJOR! You\'re at #{worldRank} in the global VRS ranking', es: '¡CLASIFICADO PARA EL MAJOR MUNDIAL! Estás en #{worldRank} en el ranking VRS mundial' },
  'Cada circuito é um': { en: 'Each circuit is a', es: 'Cada circuito es un' },
  'Cada circuito é um tier. Você joga no seu tier ou abaixo; vencer o seu circuito te promove, terminar no fundo te rebaixa. Só o Tier 1 dá vaga no Major.': { en: 'Each circuit is a tier. You play in your tier or below; winning your circuit promotes you, finishing low demotes you. Only Tier 1 gives a spot at the Major.', es: 'Cada circuito es un tier. Juegas en tu tier o inferior; ganar tu circuito te promueve, terminar abajo te degrada. Solo Tier 1 da plaza al Major.' },
  'Caixa': { en: 'Cash', es: 'Caja' },
  'Caixa de entrada': { en: 'Inbox', es: 'Bandeja de entrada' },
  'Caixa do clube': { en: 'Team cash', es: 'Caja del equipo' },
  'Caixa insuficiente': { en: 'Insufficient cash', es: 'Caja insuficiente' },
  'Caixa pra acordos:': { en: 'Deal budget:', es: 'Presupuesto para acuerdos:' },
  'Calendário': { en: 'Calendar', es: 'Calendario' },
  'Campanha': { en: 'Record', es: 'Campaña' },
  'Campeonato': { en: 'Tournament', es: 'Torneo' },
  'Campeão': { en: 'Champion', es: 'Campeón' },
  'Cancelar': { en: 'Cancel', es: 'Cancelar' },
  'Cena mundial': { en: 'World Scene', es: 'Escena mundial' },
  'Cena mundial · Split': { en: 'World scene · Split', es: 'Escena mundial · Split' },
  'Cenário': { en: 'Scene', es: 'Escena' },
  'Chave': { en: 'Bracket', es: 'Llave' },
  'Chegar ao Tier 1': { en: 'Reach Tier 1', es: 'Llegar al Tier 1' },
  'Classificado': { en: 'Qualified', es: 'Clasificado' },
  'Classificados': { en: 'Qualified', es: 'Clasificados' },
  'Classificar para o Major Mundial': { en: 'Qualify for the World Major', es: 'Clasificar para el Major Mundial' },
  'Classificar pro Major': { en: 'Qualify for Major', es: 'Clasificar para el Major' },
  'Classificação': { en: 'Standings', es: 'Clasificación' },
  'Clique em qualquer partida finalizada para ver o placar mapa a mapa.': { en: 'Click any finished match to see the map-by-map scoreboard.', es: 'Haz clic en cualquier partida terminada para ver el marcador mapa a mapa.' },
  'Clique em um time para ver elenco, técnico e força.': { en: 'Click a team to see roster, coach and strength.', es: 'Haz clic en un equipo para ver plantilla, entrenador y fuerza.' },
  'Clique num confronto concluído pra ver o placar completo da série.': { en: 'Click a finished matchup to see the full series score.', es: 'Haz clic en un enfrentamiento completado para ver el marcador completo de la serie.' },
  'Clique num jogo concluído pra ver o placar.': { en: 'Click a finished match to see the score.', es: 'Haz clic en un juego completado para ver el marcador.' },
  'Coach': { en: 'Coach', es: 'Entrenador' },
  'Comece por um desafio': { en: 'Start with a challenge', es: 'Comienza con un desafío' },
  'Começar': { en: 'Start', es: 'Comenzar' },
  'Começar do zero (org sem line ativa)': { en: 'Start from scratch (org without active roster)', es: 'Comienza desde cero (org sin plantilla activa)' },
  'Começar uma nova carreira': { en: 'Start a New Career', es: 'Comenzar una Nueva Carrera' },
  'Como funciona a temporada': { en: 'How the season works', es: 'Cómo funciona la temporada' },
  'Competição': { en: 'Competition', es: 'Competición' },
  'Compromisso de': { en: 'Commitment of', es: 'Compromiso de' },
  'Confiança': { en: 'Confidence', es: 'Confianza' },
  'Confirmar e abrir o mercado': { en: 'Confirm and open transfer market', es: 'Confirmar y abrir el mercado' },
  'Confronto equilibrado': { en: 'Even matchup', es: 'Confronto equilibrado' },
  'Contente': { en: 'Happy', es: 'Contento' },
  'Continuar →': { en: 'Continue →', es: 'Continuar →' },
  'Contratação': { en: 'Signing', es: 'Contratación' },
  'Contrate 5 jogadores e 1 coach dentro do orçamento. Só jogadores dos elencos atuais (CS2). Clique num contratado para dispensar: contratação desta janela tem reembolso integral; jogador do seu elenco é vendido por 85% do valor.': { en: 'Sign 5 players and 1 coach within budget. Only players from current rosters (CS2). Click a signed player to release: signings from this window have full refund; a player from your roster is sold for 85% value.', es: 'Firma 5 jugadores y 1 entrenador dentro del presupuesto. Solo jugadores de plantillas actuales (CS2). Haz clic en un jugador contratado para liberarlo: contrataciones de esta ventana tienen reembolso completo; un jugador de tu plantilla se vende por el 85% del valor.' },
  'Contrato': { en: 'Contract', es: 'Contrato' },
  'Contrato até o Split': { en: 'Contract until Split', es: 'Contrato hasta Split' },
  'Contrato encerrado: clique para sair': { en: 'Contract ended: click to exit', es: 'Contrato finalizado: haz clic para salir' },
  'Contrato vencido:': { en: 'Contract expired:', es: 'Contrato vencido:' },
  'Contratos do elenco': { en: 'Roster contracts', es: 'Contratos del roster' },
  'Cores (primária / secundária)': { en: 'Colors (primary / secondary)', es: 'Colores (primario / secundario)' },
  'Crie sua org nos': { en: 'Create your org in the', es: 'Crea tu org en' },
  'Custo das renovações:': { en: 'Renewal cost:', es: 'Costo de renovaciones:' },
  'Círculo': { en: 'Circle', es: 'Círculo' },
  'Decisão · MD3': { en: 'Decider · MD3', es: 'Desempate · MD3' },
  'Defina o elenco e o circuito para receber o objetivo da diretoria.': { en: 'Set your roster and circuit to receive the board\'s objective.', es: 'Establece tu plantilla y circuito para recibir el objetivo de la junta.' },
  'Derrota': { en: 'Loss', es: 'Derrota' },
  'Desafios de carreira': { en: 'Career challenges', es: 'Desafíos de carrera' },
  'Desfazer': { en: 'Undo', es: 'Deshacer' },
  'Desistir': { en: 'Give up', es: 'Desistir' },
  'Destaque do seu time': { en: 'Team Highlight', es: 'Destaque de tu Equipo' },
  'Destaques da temporada': { en: 'Season highlights', es: 'Destaques de la temporada' },
  'Dinheiro:': { en: 'Cash:', es: 'Efectivo:' },
  'Diretoria': { en: 'Board', es: 'Directiva' },
  'Diretoria cobra resultados': { en: 'Board demands results', es: 'Directiva exige resultados' },
  'Diretoria satisfeita': { en: 'Board satisfied', es: 'Directiva satisfecha' },
  'Disciplinado': { en: 'Disciplined', es: 'Disciplinado' },
  'Dispensar': { en: 'Release', es: 'Expulsar' },
  'Dispensar o prospecto da academia': { en: 'Release the prospect from academy', es: 'Expulsar el prospecto de la academia' },
  'Disputar o': { en: 'Enter', es: 'Participar en' },
  'Disputar o Major Mundial': { en: 'Dispute the World Major', es: 'Disputar el Major Mundial' },
  'Divisões · Split {split} · você está no': { en: 'Divisions · Split {split} · you are in', es: 'Divisiones · Split {split} · estás en' },
  'Elenco': { en: 'Roster', es: 'Plantilla' },
  'Elenco cheio — sai do time:': { en: 'Roster full — leaving the team:', es: 'Roster lleno — sale del equipo:' },
  'Elenco forte, caixa curto': { en: 'Strong roster, tight cash', es: 'Plantilla fuerte, caja ajustada' },
  'Elenco mediano, caixa folgado': { en: 'Mid roster, comfortable cash', es: 'Plantilla media, caja holgada' },
  'Eles são favoritos': { en: 'They are favorites', es: 'Ellos son favoritos' },
  'Eliminados': { en: 'Eliminated', es: 'Eliminados' },
  'Eliminação (4º)': { en: 'Elimination (4th)', es: 'Eliminación (4º)' },
  'Em ascensão:': { en: 'On the rise:', es: 'En ascenso:' },
  'Em queda:': { en: 'Declining:', es: 'En caída:' },
  'Emblema': { en: 'Emblem', es: 'Emblema' },
  'Entendi': { en: 'Got it', es: 'Entendido' },
  'Entre temporadas o elenco evolui: jogador em ascensão melhora, no auge oscila e veterano em declínio cai. O valor e o salário acompanham os atributos: segurar um veterano caro (ou vender no pico) é decisão sua.': { en: 'Between seasons your roster evolves: rising players improve, prime players fluctuate, and declining veterans drop. Value and wage track attributes: holding an expensive veteran (or selling at peak) is your call.', es: 'Entre temporadas tu plantilla evoluciona: jugadores en ascenso mejoran, jugadores en su apogeo fluctúan, y veteranos en declive caen. Valor y salario acompañan atributos: mantener un veterano caro (o vender en el pico) es tu decisión.' },
  'Escolha': { en: 'Choose', es: 'Elige' },
  'Escolha o campeonato': { en: 'Choose the circuit', es: 'Elige el circuito' },
  'Escolha um coach.': { en: 'Choose a coach.', es: 'Elige un entrenador.' },
  'Escolha um desafio (uma org pronta, com contexto e metas próprias) ou funde a sua do zero. Cada desafio traz objetivos pra cumprir ao longo da campanha.': { en: 'Pick a challenge (a ready-made org with context and objectives) or found your own from scratch. Each challenge brings goals to achieve throughout the campaign.', es: 'Elige un desafío (una organización lista con contexto y objetivos) o funda la tuya desde cero. Cada desafío trae objetivos a cumplir durante la campaña.' },
  'Escolha uma': { en: 'Choose a', es: 'Elige una' },
  'Escudo': { en: 'Shield', es: 'Escudo' },
  'Estatísticas de carreira': { en: 'Career stats', es: 'Estadísticas de carrera' },
  'Este circuito não usa fase de grupos GSL.': { en: 'This circuit doesn\'t use GSL group stage.', es: 'Este circuito no usa fase de grupos GSL.' },
  'Estes contratos venceram. Decida cada um:': { en: 'These contracts have expired. Decide for each one:', es: 'Estos contratos han vencido. Decide para cada uno:' },
  'Estrela': { en: 'Star', es: 'Estrella' },
  'Estuda o adversário: defesa mais sólida. Bom contra times melhores.': { en: 'Studies the opponent: stronger defense. Good against better teams.', es: 'Estudia al oponente: defensa más sólida. Bueno contra equipos mejores.' },
  'Evolução do elenco na janela': { en: 'Roster evolution this window', es: 'Evolución de plantilla en la ventana' },
  'FASE DE PLAYOFFS': { en: 'PLAYOFF STAGE', es: 'FASE DE PLAYOFFS' },
  'FASE SUÍÇA': { en: 'SWISS STAGE', es: 'FASE SUIZA' },
  'FURIA: manter o Brasil no topo': { en: 'FURIA: keeping Brazil on top', es: 'FURIA: mantener a Brasil en la cima' },
  'FaZe: a reconstrução': { en: 'FaZe: the rebuild', es: 'FaZe: la reconstrucción' },
  'Faltam': { en: 'Missing', es: 'Faltan' },
  'Fazer proposta': { en: 'Make offer', es: 'Hacer oferta' },
  'Fechar': { en: 'Close', es: 'Cerrar' },
  'Fechar acordo': { en: 'Close deal', es: 'Cerrar acuerdo' },
  'Fechar elenco e escolher o campeonato': { en: 'Close roster and choose tournament', es: 'Cerrar plantilla y elegir torneo' },
  'Filtrar por nacionalidade': { en: 'Filter by nationality', es: 'Filtrar por nacionalidad' },
  'Fim de ciclo': { en: 'End of Era', es: 'Fin de Ciclo' },
  'Finanças': { en: 'Finances', es: 'Finanzas' },
  'Finanças da': { en: 'Finances of', es: 'Finanzas de' },
  'Finanças ⚠️': { en: 'Finances ⚠️', es: 'Finanzas ⚠️' },
  'FlyQuest: o sonho norte-americano': { en: 'FlyQuest: the American dream', es: 'FlyQuest: el sueño norteamericano' },
  'Foco no mapa forte': { en: 'Map focus', es: 'Enfoque en el mapa fuerte' },
  'Folha salarial por split': { en: 'Wage bill per split', es: 'Nómina por split' },
  'Forma': { en: 'Form', es: 'Forma' },
  'Força': { en: 'Strength', es: 'Fuerza' },
  'Fundar organização (modo carreira)': { en: 'Found organization (career mode)', es: 'Fundar organización (modo carrera)' },
  'FÃS': { en: 'FANS', es: 'FANS' },
  'GRANDE FINAL': { en: 'GRAND FINAL', es: 'GRAN FINAL' },
  'Generosa': { en: 'Generous', es: 'Generosa' },
  'Gerencie entre os splits': { en: 'Manage between splits', es: 'Gestiona entre splits' },
  'Gigante norte-americana fora do CS2. Marca enorme e caixa cheio pra reconstruir do zero.': { en: 'North American giant out of CS2. Huge brand and deep pockets to rebuild from scratch.', es: 'Gigante norteamericano fuera de CS2. Marca enorme y mucho dinero para reconstruir desde cero.' },
  'Grande final · MD5': { en: 'Grand final · MD5', es: 'Gran final · MD5' },
  'Grupo {g.key} · top 2 avançam': { en: 'Group {g.key} · top 2 advance', es: 'Grupo {g.key} · top 2 avanzan' },
  'Hexágono': { en: 'Hexagon', es: 'Hexágono' },
  'História da org': { en: 'Org History', es: 'Historia de la org' },
  'Idade': { en: 'Age', es: 'Edad' },
  'Imperial: a última dança': { en: 'Imperial: the last dance', es: 'Imperial: el último baile' },
  'Incluir na troca (abate o valor em dinheiro)': { en: 'Include in swap (reduces cash value)', es: 'Incluir en intercambio (reduce el valor en efectivo)' },
  'Indiferente': { en: 'Indifferent', es: 'Indiferente' },
  'Insatisfeito': { en: 'Unhappy', es: 'Insatisfecho' },
  'Insistir': { en: 'Insist', es: 'Insistir' },
  'Início': { en: 'Home', es: 'Inicio' },
  'Janela de transferências só entre temporadas': { en: 'Transfer window only between seasons', es: 'Ventana de transferencias solo entre temporadas' },
  'Jogador': { en: 'Player', es: 'Jugador' },
  'Jogo seguro e constante. Baixa variância, base sólida.': { en: 'Safe and consistent play. Low variance, solid foundation.', es: 'Juego seguro y consistente. Baja varianza, fundación sólida.' },
  'Jovem em ascensão melhora entre temporadas; veterano cai': { en: 'Rising young improve between seasons; veterans decline', es: 'Jóvenes en ascenso mejoran entre temporadas; veteranos caen' },
  'Justa': { en: 'Fair', es: 'Justa' },
  'Legacy: a nova geração': { en: 'Legacy: the new generation', es: 'Legacy: la nueva generación' },
  'Levar a SAW ao Tier 1': { en: 'Take SAW to Tier 1', es: 'Llevar a SAW al Tier 1' },
  'Liberar': { en: 'Release', es: 'Liberar' },
  'Liberar todos': { en: 'Release all', es: 'Liberar todos' },
  'Limpar filtros': { en: 'Clear filters', es: 'Borrar filtros' },
  'Losango': { en: 'Diamond', es: 'Rombo' },
  'MIBR: reerguer a marca': { en: 'MIBR: raising the brand', es: 'MIBR: elevar la marca' },
  'MOUZ: a nova geração': { en: 'MOUZ: the new generation', es: 'MOUZ: la nueva generación' },
  'MVP de torneio no ano': { en: 'tournament MVP this year', es: 'MVP de torneo este año' },
  'MVP do circuito': { en: 'Circuit MVP', es: 'MVP del Circuito' },
  'Major Mundial': { en: 'World Major', es: 'Major Mundial' },
  'Major Mundial - resultado': { en: 'World Major - Results', es: 'Major Mundial - Resultados' },
  'Major Mundial a cada': { en: 'World Major every', es: 'Major Mundial cada' },
  'Major Mundial no Split': { en: 'World Major on Split', es: 'Major Mundial en el Split' },
  'Mapa': { en: 'Map', es: 'Mapa' },
  'Mapas na temporada': { en: 'Maps this season', es: 'Mapas esta temporada' },
  'Mata-mata MD3 (final MD5).': { en: 'Playoffs MD3 (grand final MD5).', es: 'Mata-mata MD3 (final MD5).' },
  'Melhores jogadores do': { en: 'Best players of', es: 'Mejores jugadores de' },
  'Mercado': { en: 'Transfer market', es: 'Mercado' },
  'Mercado (': { en: 'Market (', es: 'Mercado (' },
  'Mercado parado por enquanto.': { en: 'Market quiet for now.', es: 'Mercado tranquilo por ahora.' },
  'Mercado · negocie com os clubes': { en: 'Market · negotiate with clubs', es: 'Mercado · negocia con los clubes' },
  'Meta da diretoria: "': { en: 'Board target: "', es: 'Meta de la directiva: "' },
  'Meu time': { en: 'My Team', es: 'Mi equipo' },
  'Moral baixa no elenco. Vitórias, renovação de contrato e títulos levantam o astral.': { en: 'Low morale in the roster. Wins, contract renewals and titles boost spirits.', es: 'Moral baja en el elenco. Las victorias, renovaciones de contrato y títulos suben la moral.' },
  'Moral:': { en: 'Morale:', es: 'Moral:' },
  'Motivado': { en: 'Motivated', es: 'Motivado' },
  'Mudar para': { en: 'Change to', es: 'Cambiar a' },
  'Mundo': { en: 'World', es: 'Mundo' },
  'Máximo de': { en: 'Max of', es: 'Máximo de' },
  'NAVI: o renascimento': { en: 'NAVI: the rebirth', es: 'NAVI: el renacimiento' },
  'Na janela você negocia reforços (até com troca de jogadores), renova contratos, treina mapas e o playbook, e forma jovens na academia. Suas decisões pesam no time.': { en: 'In the window you negotiate signings (even with player swaps), renew contracts, train maps and playbook, and develop young talent in the academy. Your decisions shape the team.', es: 'En la ventana negocias refuerzos (incluso con intercambios), renuevas contratos, entrenan mapas y playbook, y formas jóvenes en la academia. Tus decisiones pesan en el equipo.' },
  'Nada nessa categoria ainda.': { en: 'Nothing in this category yet.', es: 'Nada en esta categoría aún.' },
  'Negociando com': { en: 'Negotiating with', es: 'Negociando con' },
  'Negociações': { en: 'Transfers', es: 'Transferencias' },
  'Nenhum jogador com esse filtro.': { en: 'No players matching this filter.', es: 'Ningún jugador coincide con este filtro.' },
  'Nenhum jogador com esses filtros.': { en: 'No players with these filters.', es: 'Sin jugadores con estos filtros.' },
  'NiP: o gigante adormecido': { en: 'NiP: the sleeping giant', es: 'NiP: el gigante dormido' },
  'Nome da organização': { en: 'Organization name', es: 'Nombre de la organización' },
  'Não ser rebaixado (longe da zona)': { en: 'Avoid relegation (stay safe)', es: 'Evita el descenso (mantente seguro)' },
  'O cenário evolui a cada split — os campeões e a ordem mudam. Clique num time pra ver elenco e mapas. Você sobe de região mudando o core do elenco (nas Finanças/Mercado).': { en: 'The scene evolves every split — the champions and the order change. Click a team to see its roster and maps. You move up regions by changing your roster core (in Finances/Market).', es: 'El escenario evoluciona cada split — los campeones y el orden cambian. Clic en un equipo para ver roster y mapas. Subes de región cambiando el core del roster (en Finanzas/Mercado).' },
  'O clube cansou da conversa: proposta baixa demais, negociação encerrada.': { en: 'The club got tired of talking: offer too low, negotiation over.', es: 'El club se cansó de hablar: oferta demasiado baja, negociación terminada.' },
  'O jogador saiu': { en: 'The player left', es: 'El jugador se fue' },
  'O projeto brasileiro de veteranos quer um último grande Major. Honre a camisa verde-amarela.': { en: 'Brazil\'s veteran project wants one last Major run. Honor the green-and-gold shirt.', es: 'El proyecto veterano brasileño quiere una última carrera en el Major. Honra la camisa verde y amarilla.' },
  'ODDIK: do acesso à elite': { en: 'ODDIK: from access to elite', es: 'ODDIK: del acceso a la élite' },
  'Objetivo cumprido': { en: 'Objective met', es: 'Objetivo cumplido' },
  'Objetivo da diretoria ({obj.text}): CUMPRIDO': { en: 'Board Objective ({obj.text}): MET', es: 'Objetivo de la Junta ({obj.text}): CUMPLIDO' },
  'Objetivo do split:': { en: 'Split objective:', es: 'Objetivo de split:' },
  'Objetivo não cumprido': { en: 'Objective missed', es: 'Objetivo no cumplido' },
  'Olheiros': { en: 'Scouts', es: 'Ojeadores' },
  'Opção de entrada: barato, mas com rating baixo': { en: 'Entry option: cheap but low rating', es: 'Opción de entrada: barata pero con rating bajo' },
  'Org lendária sem elenco ativo. Verba boa pra recolocar o nome no topo.': { en: 'Legendary org without active roster. Good budget to put the name back on top.', es: 'Org legendaria sin plantilla activa. Buen presupuesto para devolver el nombre a la cima.' },
  'Organização': { en: 'Organization', es: 'Organización' },
  'Orçamento estourado.': { en: 'Budget exceeded.', es: 'Presupuesto agotado.' },
  'Os destaques aparecem após as primeiras partidas.': { en: 'Highlights appear after the first matches.', es: 'Los destacados aparecen después de los primeros partidos.' },
  'Os jogadores saíram': { en: 'The players left', es: 'Los jugadores se fueron' },
  'Os resultados ficaram abaixo do esperado e a confiança da diretoria chegou ao fundo. Sua passagem termina aqui — mas toda lenda recomeça.': { en: 'Results fell short of expectations and the board\'s confidence hit rock bottom. Your time ends here — but every legend starts anew.', es: 'Los resultados quedaron por debajo de las expectativas y la confianza de la junta llegó al fondo. Tu paso termina aquí — pero toda leyenda comienza de nuevo.' },
  'POSIÇÃO': { en: 'STANDING', es: 'POSICIÓN' },
  'PRESTÍGIO': { en: 'PRESTIGE', es: 'PRESTIGIO' },
  'PRÓXIMA PARTIDA ·': { en: 'NEXT MATCH ·', es: 'PRÓXIMO PARTIDO ·' },
  'Pagar folha ({formatMoney(payroll)}) e ir pro Split {save.split + 1}': { en: 'Pay Payroll ({formatMoney(payroll)}) and Go to Split {save.split + 1}', es: 'Pagar Nómina ({formatMoney(payroll)}) e Ir al Split {save.split + 1}' },
  'Pagar folha e ir pro Split': { en: 'Pay wages and advance to Split', es: 'Pagar nómina e ir a la Split' },
  'Patrocinadores (': { en: 'Sponsors (', es: 'Patrocinadores (' },
  'Patrocínio / split': { en: 'Sponsorship / split', es: 'Patrocinio / split' },
  'Pedida do clube': { en: 'Club asking price', es: 'Precio pedido del club' },
  'Pontos de ranking (VRS)': { en: 'Ranking points (VRS)', es: 'Puntos de ranking (VRS)' },
  'Por região': { en: 'By region', es: 'Por región' },
  'Posição': { en: 'Position', es: 'Posición' },
  'Potencial': { en: 'Potential', es: 'Potencial' },
  'Potencial (teto de OVR)': { en: 'Potential (OVR ceiling)', es: 'Potencial (techo de OVR)' },
  'Premiação de fim de temporada · Temporada': { en: 'End of season awards · Season', es: 'Premios de fin de temporada · Temporada' },
  'Premiação do Top 20 HLTV': { en: 'Top 20 HLTV prize money', es: 'Premio del Top 20 HLTV' },
  'Premiação: {formatMoney(mr.prize)} · VRS: {mr.vrs} pts · +1 título!': { en: 'Prize: {formatMoney(mr.prize)} · VRS: {mr.vrs} pts · +1 title!', es: 'Premio: {formatMoney(mr.prize)} · VRS: {mr.vrs} pts · +1 título!' },
  'Premiação: {formatMoney(prize)} · VRS: {vrsGain} pts · Folha: {formatMoney(payroll)}': { en: 'Prize: {formatMoney(prize)} · VRS: {vrsGain} pts · Payroll: {formatMoney(payroll)}', es: 'Premio: {formatMoney(prize)} · VRS: {vrsGain} pts · Nómina: {formatMoney(payroll)}' },
  'Pressão nas aberturas: teto alto, mais arriscado.': { en: 'Opening pressure: high ceiling, riskier.', es: 'Presión en las aperturas: techo alto, más arriesgado.' },
  'Prestígio da org: cresce com títulos, Major, tier e VRS; atrai mais patrocínio': { en: 'Org prestige: grows with titles, Major, tier and VRS; attracts sponsors', es: 'Prestigio de la org: crece con títulos, Major, tier y VRS; atrae patrocinadores' },
  'Proposta muito abaixo do valor. O clube recusou na hora.': { en: 'Offer way below value. The club refused immediately.', es: 'Oferta muy por debajo del valor. El club rechazó de inmediato.' },
  'Proposta recebida': { en: 'Offer received', es: 'Oferta recibida' },
  'Prêmio': { en: 'Prize', es: 'Premio' },
  'Prêmios na história': { en: 'Prize money all-time', es: 'Premios en la historia' },
  'Próximo': { en: 'Next', es: 'Siguiente' },
  'Próximos splits': { en: 'Upcoming splits', es: 'Próximos splits' },
  'Pular': { en: 'Skip', es: 'Saltar' },
  'Pular ⏭': { en: 'Skip ⏭', es: 'Saltar ⏭' },
  'Puxa o veto pro seu melhor mapa e joga mais forte nele.': { en: 'Pulls veto toward your best map and plays stronger on it.', es: 'Tira el veto hacia tu mejor mapa y juega más fuerte en él.' },
  'QUARTAS DE FINAL': { en: 'QUARTERFINALS', es: 'CUARTOS DE FINAL' },
  'Quartas': { en: 'Quarterfinals', es: 'Cuartos' },
  'Quartas · MD3': { en: 'Quarterfinals · MD3', es: 'Cuartos · MD3' },
  'Quer realocar a org para a': { en: 'Want to relocate the org to', es: 'Quieres reubicar la org a' },
  'Raio': { en: 'Bolt', es: 'Rayo' },
  'Ranking HLTV — Top 20 do ano': { en: 'HLTV Ranking — Top 20 of the Year', es: 'Ranking HLTV — Top 20 del año' },
  'Ranking VRS': { en: 'VRS Ranking', es: 'Ranking VRS' },
  'Ranking VRS mundial': { en: 'Global VRS Ranking', es: 'Ranking VRS mundial' },
  'Recusar': { en: 'Refuse', es: 'Rechazar' },
  'Reforços confirmados na janela': { en: 'Confirmed reinforcements at transfer window', es: 'Refuerzos confirmados en ventana de traspasos' },
  'Relatório do olheiro': { en: 'Scout Report', es: 'Informe del explorador' },
  'Renovar': { en: 'Renew', es: 'Renovar' },
  'Renovar todos': { en: 'Renew all', es: 'Renovar todos' },
  'Renovação de contratos': { en: 'Contract renewals', es: 'Renovación de contratos' },
  'Renove em': { en: 'Renew in', es: 'Renueva en' },
  'Requer': { en: 'Requires', es: 'Requiere' },
  'Resetar a carreira e começar do ZERO? Isso apaga todo o seu progresso (org, elenco, títulos, dinheiro). Não dá pra desfazer.': { en: 'Reset career and start from ZERO? This erases all your progress (org, roster, titles, money). Cannot be undone.', es: '¿Reiniciar carrera y empezar desde CERO? Esto borra todo tu progreso (org, plantilla, títulos, dinero). No se puede deshacer.' },
  'Resultados': { en: 'Results', es: 'Resultados' },
  'Revele jovens talentos, deixe um em': { en: 'Scout young talent, keep one', es: 'Recluta jóvenes talentos, mantén uno' },
  'Rever o tutorial': { en: 'Review tutorial', es: 'Revisar tutorial' },
  'Revoltado': { en: 'Angry', es: 'Furioso' },
  'Rodada': { en: 'Round', es: 'Ronda' },
  'Rodada concluída. Avançando…': { en: 'Round finished. Moving on…', es: 'Ronda completada. Avanzando…' },
  'Rodadas jogadas': { en: 'Rounds played', es: 'Rondas jugadas' },
  'Rounds': { en: 'Rounds', es: 'Rondas' },
  'Rumores da janela': { en: 'Window rumors', es: 'Rumores de la ventana' },
  'Rumores da próxima janela': { en: 'Next window rumors', es: 'Rumores de la próxima ventana' },
  'Rumores para a próxima janela': { en: 'Transfer Window Rumors', es: 'Rumores de la Próxima Ventana' },
  'SAW: o orgulho de Portugal': { en: 'SAW: Portugal\'s pride', es: 'SAW: el orgullo de Portugal' },
  'Sair': { en: 'Exit', es: 'Salir' },
  'Saldo / split': { en: 'Net / split', es: 'Saldo / split' },
  'Saldo de rounds': { en: 'Round diff', es: 'Diferencia de rounds' },
  'Salvar elenco': { en: 'Save roster', es: 'Guardar plantilla' },
  'Salário / split': { en: 'Wage / split', es: 'Salario / split' },
  'Salário/split': { en: 'Wage/split', es: 'Salario/split' },
  'Saída da base do CS brasileiro, a ODDIK quer provar que o acesso vira elite. Suba os tiers.': { en: 'Rising from Brazilian grassroots, ODDIK wants to prove that access becomes elite. Climb the tiers.', es: 'Surgida de las bases del CS brasileño, ODDIK quiere probar que el acceso se convierte en élite. Sube los tiers.' },
  'Saídas por fim de contrato': { en: 'Contract Expirations', es: 'Salidas por Fin de Contrato' },
  'Saíram por proposta aceita:': { en: 'Left on an accepted offer:', es: 'Salieron por oferta aceptada:' },
  'Sem caixa pra renovar todos. Libere alguém pra caber no orçamento.': { en: 'Not enough cash to renew everyone. Release someone to fit the budget.', es: 'Sin caja para renovar todos. Libera a alguien para ajustarte al presupuesto.' },
  'Sem novidades por enquanto. As manchetes aparecem ao longo da carreira (resultados, diretoria, mercado, cenário e social).': { en: 'No updates yet. Headlines appear throughout your career (results, board, market, scenario and social).', es: 'Sin novedades aún. Los titulares aparecen a lo largo de tu carrera (resultados, junta, mercado, escenario y social).' },
  'Sem partidas jogadas ainda nesta temporada.': { en: 'No matches played yet this season.', es: 'Sin partidos jugados aún esta temporada.' },
  'Sem renovação, saíram do elenco:': { en: 'Not renewed, left the roster:', es: 'Sin renovación, salieron del roster:' },
  'Sem renovação, saíram do elenco: {released.join(\', \')}.': { en: 'Without renewal, they left the roster: {released.join(\', \')}.', es: 'Sin renovación, salieron del elenco: {released.join(\', \')}.' },
  'Semi': { en: 'Semifinal', es: 'Semifinal' },
  'Semifinal · MD3': { en: 'Semifinals · MD3', es: 'Semifinal · MD3' },
  'Seu core mudou: agora é da': { en: 'Your core changed: now it\'s from', es: 'Tu core cambió: ahora es de' },
  'Seu elenco': { en: 'Your roster', es: 'Tu roster' },
  'Seu elenco (': { en: 'Your roster (', es: 'Tu plantilla (' },
  'Seu elenco evolui entre temporadas': { en: 'Your roster develops between seasons', es: 'Tu roster evoluciona entre temporadas' },
  'Seus destaques no split': { en: 'Your standouts this split', es: 'Tus destaques en el split' },
  'Slots cheios': { en: 'Slots full', es: 'Plazas llenas' },
  'Sua Organização': { en: 'Your Organization', es: 'Tu Organización' },
  'Sua academia está vazia. Revele um prospecto pra começar a formar a próxima geração — eles começam crus (OVR baixo) mas evoluem treinando.': { en: 'Your academy is empty. Scout a prospect to start developing the next generation — they start raw (low OVR) but grow through training.', es: 'Tu academia está vacía. Recluta un prospecto para comenzar a formar la próxima generación — comienzan sin pulir (OVR bajo) pero evolucionan entrenando.' },
  'Sua org representou o circuito no Major mundial. Volte mais forte no próximo split.': { en: 'Your org represented the circuit at the World Major. Come back stronger next split.', es: 'Tu org representó el circuito en el Major mundial. Vuelve más fuerte el próximo split.' },
  'Sua organização ainda não encerrou nenhum split. A história começa agora.': { en: 'Your organization hasn\'t closed out a single split yet. The story starts now.', es: 'Tu organización aún no ha cerrado ningún split. La historia empieza ahora.' },
  'Sua organização é CAMPEÃ MUNDIAL! O nome entrou para a história do CS.': { en: 'Your organization is WORLD CHAMPION! Your name goes down in CS history.', es: '¡Tu organización es CAMPEONA MUNDIAL! Tu nombre entra en la historia del CS.' },
  'Sua próxima partida:': { en: 'Your next match:', es: 'Tu próxima partida:' },
  'Suba ao': { en: 'Rise to', es: 'Sube al' },
  'Suba no ranking e vá ao Major': { en: 'Climb the ranking and reach the Major', es: 'Sube en el ranking y llega al Major' },
  'Subir ao Tier 1': { en: 'Reach Tier 1', es: 'Llegar al Tier 1' },
  'Subir de divisão coloca a org mais perto do Major. Patrocinadores de olho.': { en: 'Climbing divisions puts the org closer to the Major. Sponsors watching.', es: 'Subir de división acerca la org al Major. Patrocinadores atentos.' },
  'Subir para o Tier 1 nesta temporada': { en: 'Reach Tier 1 this season', es: 'Llegar al Tier 1 esta temporada' },
  'Suíça': { en: 'Swiss', es: 'Suizo' },
  'Só em split de Major · próximo no Split': { en: 'Only on a Major split · next on Split', es: 'Solo en split de Major · próximo en el Split' },
  'Tag (até 4 letras)': { en: 'Tag (up to 4 letters)', es: 'Tag (hasta 4 letras)' },
  'Temporada': { en: 'Season', es: 'Temporada' },
  'Temporada atual · Split': { en: 'Current season · Split', es: 'Temporada actual · Split' },
  'Temporada para esquecer: a queda de divisão pressiona o elenco e o caixa.': { en: 'Season to forget: division drop pressures the roster and wallet.', es: 'Temporada para olvidar: la caída de división presiona el elenco y la caja.' },
  'Terminar no top 4 do circuito de elite': { en: 'Finish top 4 in the elite circuit', es: 'Termina en top 4 del circuito de élite' },
  'Terminar no top 4 e brigar pelo acesso': { en: 'Finish top 4 and fight for promotion', es: 'Termina en top 4 y lucha por el ascenso' },
  'Terminar top 4 num circuito de elite': { en: 'Finish top 4 in an elite circuit', es: 'Terminar en top 4 en un circuito de élite' },
  'Tier 1 mundial ·': { en: 'Tier 1 world ·', es: 'Tier 1 mundial ·' },
  'Tier 1 · Elite': { en: 'Tier 1 · Elite', es: 'Tier 1 · Élite' },
  'Tier 2 mundial ·': { en: 'Tier 2 world ·', es: 'Tier 2 mundial ·' },
  'Tier 3 · Acesso': { en: 'Tier 3 · Access', es: 'Tier 3 · Acceso' },
  'Times confirmados no': { en: 'Confirmed teams in', es: 'Equipos confirmados en' },
  'Todas': { en: 'All', es: 'Todos' },
  'Top 20 HLTV · melhores da temporada': { en: 'Top 20 HLTV · best of the season', es: 'Top 20 HLTV · mejores de la temporada' },
  'Top 3 HLTV da temporada': { en: 'Top 3 HLTV of the Season', es: 'Top 3 HLTV de la Temporada' },
  'Top 4 num circuito': { en: 'Top 4 in a circuit', es: 'Top 4 en un circuito' },
  'Top 4 num circuito de elite': { en: 'Top 4 in an elite circuit', es: 'Top 4 en un circuito de élite' },
  'Top 8 avançam ao próximo stage.': { en: 'Top 8 advance to next stage.', es: 'Top 8 avanzan a la siguiente ronda.' },
  'Torcida da organização': { en: 'Org fanbase', es: 'Afición de la org' },
  'Tradicional, sem line desde 2022. Orçamento mediano: monte com inteligência.': { en: 'Traditional, no roster since 2022. Mid-tier budget: build smart.', es: 'Tradicional, sin plantilla desde 2022. Presupuesto mediano: construye inteligentemente.' },
  'Treinar': { en: 'Train', es: 'Entrenar' },
  'Treine até': { en: 'Train up to', es: 'Entrena hasta' },
  'Troféu': { en: 'Trophy', es: 'Trofeo' },
  'TÍTULOS': { en: 'TITLES', es: 'TÍTULOS' },
  'Tá pronto!': { en: 'Ready to go!', es: '¡Listo para ir!' },
  'Técnico Iniciante': { en: 'Rookie Coach', es: 'Técnico Novato' },
  'Técnico:': { en: 'Coach:', es: 'Entrenador:' },
  'Título conquistado! A torcida foi à loucura e a diretoria respira aliviada.': { en: 'Title won! The fans went crazy and the board breathes easy.', es: '¡Título ganado! Los aficionados se volvieron locos y la directiva respira aliviada.' },
  'Títulos': { en: 'Titles', es: 'Títulos' },
  'Títulos de circuito': { en: 'Circuit titles', es: 'Títulos de circuito' },
  'Um dos nomes mais tradicionais da Suécia vive longe do topo. Reacenda a lenda dos ninjas.': { en: 'One of Sweden\'s most traditional names lives far from the top. Reignite the ninjas legend.', es: 'Uno de los nombres más tradicionales de Suecia vive lejos de la cima. Reavivar la leyenda de los ninjas.' },
  'V-D': { en: 'W-L', es: 'G-P' },
  'VICE-CAMPEÃO': { en: 'RUNNER-UP', es: 'SUBCAMPEÓN' },
  'VOCÊ FOI DEMITIDO': { en: 'YOU WERE FIRED', es: 'FUISTE DESPEDIDO' },
  'Vaga final (2º/3º)': { en: 'Finals spot (2nd/3rd)', es: 'Plaza de finales (2º/3º)' },
  'Valor da troca:': { en: 'Swap value:', es: 'Valor del intercambio:' },
  'Valor de mercado': { en: 'Market value', es: 'Valor de mercado' },
  'Vencedores (1º)': { en: 'Winners (1st)', es: 'Ganadores (1º)' },
  'Vencedores / Eliminação · MD3': { en: 'Winners / Elimination · MD3', es: 'Ganadores / Eliminación · MD3' },
  'Vencedores · Eliminação · MD3': { en: 'Winners / Elimination · MD3', es: 'Ganadores / Eliminación · MD3' },
  'Vencer um campeonato': { en: 'Win a tournament', es: 'Ganar un torneo' },
  'Vendas confirmadas na janela': { en: 'Confirmed sales at transfer window', es: 'Ventas confirmadas en ventana de traspasos' },
  'Vender': { en: 'Sell', es: 'Vender' },
  'Vender enche o caixa, mas você fica com 4 e': { en: 'Selling fills your cash, but you\'re left with 4 and', es: 'Vender llena tu caja, pero te quedas con 4 y' },
  'Ver estatísticas da série': { en: 'View series stats', es: 'Ver estadísticas de la serie' },
  'Ver resultado do split →': { en: 'View split results →', es: 'Ver resultado de la split →' },
  'Ver stats': { en: 'View stats', es: 'Ver estadísticas' },
  'Ver tudo →': { en: 'See all →', es: 'Ver todo →' },
  'Vestiário:': { en: 'Locker room:', es: 'Vestuario:' },
  'Vice': { en: 'Runner-up', es: 'Subcampeón' },
  'Visão geral': { en: 'Overview', es: 'Resumen' },
  'Vitória!': { en: 'Victory!', es: '¡Victoria!' },
  'Você assume uma organização de Counter-Strike e leva ela do zero até o Major. Monta o elenco, joga os campeonatos e gerencia tudo entre as temporadas.': { en: 'You lead a Counter-Strike organization from nothing to the Major. Build your roster, compete in tournaments, and manage everything between seasons.', es: 'Diriges una organización de Counter-Strike desde cero hasta el Major. Construye tu plantilla, compite en torneos y gestiona todo entre temporadas.' },
  'Você entrou no': { en: 'You entered the', es: 'Entraste en la' },
  'Você está dentro do top {MAJOR_VRS_CUT} do VRS mundial (#{worldRank}) — vaga no Major encaminhada! O Major acontece a cada {MAJOR_EVERY} splits; o próximo é no fim do Split {nextMajorSplit}. Mantenha o nível.': { en: 'You\'re in the top {MAJOR_VRS_CUT} of the global VRS ranking (#{worldRank}) — Major spot secured! The Major happens every {MAJOR_EVERY} splits; next is at the end of Split {nextMajorSplit}. Keep your level up.', es: 'Estás en el top {MAJOR_VRS_CUT} del ranking VRS mundial (#{worldRank}) — ¡plaza en el Major confirmada! El Major sucede cada {MAJOR_EVERY} splits; el próximo es a fin de Split {nextMajorSplit}. Mantén tu nivel.' },
  'Você está em': { en: 'You\'re in', es: 'Estás en' },
  'Você ganha pontos de VRS vencendo eventos fortes — ganhar de time fraco rende pouco. Os melhores do ranking mundial vão ao Major, que fecha a temporada.': { en: 'You earn VRS points by winning strong events — beating weak teams yields little. The top players worldwide go to the Major, which closes the season.', es: 'Ganas puntos VRS ganando eventos fuertes — vencer equipos débiles da poco. Los mejores del ranking mundial van al Major, que cierra la temporada.' },
  'Você precisa estar no': { en: 'You must be in', es: 'Debes estar en' },
  'Você é o favorito': { en: 'You are the favorite', es: 'Eres el favorito' },
  'Você:': { en: 'You:', es: 'Tú:' },
  'Voltar': { en: 'Back', es: 'Volver' },
  'Voltar ao Tier 1': { en: 'Return to Tier 1', es: 'Volver al Tier 1' },
  'a definir': { en: 'to be decided', es: 'por definir' },
  'a final': { en: 'the finals', es: 'la final' },
  'a secundária colore o texto/emblema': { en: 'secondary colors the text/emblem', es: 'el secundario colorea el texto/emblema' },
  'aceitou a oferta de': { en: 'accepted the offer of', es: 'aceptó la oferta de' },
  'anos': { en: 'years old', es: 'años' },
  'arT lidera a nova safra do Brasil. Transforme a Legacy numa potência mundial de verdade.': { en: 'arT leads Brazil\'s new wave. Transform Legacy into a real world power.', es: 'arT lidera la nueva ola de Brasil. Transforma Legacy en una potencia mundial real.' },
  'até Split': { en: 'until Split', es: 'hasta Split' },
  'bônus +{formatMoney(objBonus)}': { en: 'bonus +{formatMoney(objBonus)}', es: 'bonificación +{formatMoney(objBonus)}' },
  'caixa': { en: 'cash', es: 'caja' },
  'campeã do': { en: 'champion of', es: 'campeón de' },
  'campeão na': { en: 'champion in the', es: 'campeón en la' },
  'chave da fase de grupos (GSL · dupla eliminação)': { en: 'group stage bracket (GSL · double elimination)', es: 'llave de fase de grupos (GSL · doble eliminación)' },
  'circuito': { en: 'circuit', es: 'circuito' },
  'clique p/ dispensar': { en: 'click to release', es: 'haz clic para liberar' },
  'começa:': { en: 'starts:', es: 'empieza:' },
  'como aparece nos campeonatos': { en: 'as it appears in tournaments', es: 'como aparece en torneos' },
  'concluído!': { en: 'completed!', es: '¡completado!' },
  'confiança': { en: 'confidence', es: 'confianza' },
  'confrontos': { en: 'matchups', es: 'enfrentamientos' },
  'contexto': { en: 'context', es: 'contexto' },
  'contratos vencem': { en: 'contracts expire', es: 'contratos vencen' },
  'cresce mais rápido a cada split rumo ao seu': { en: 'grows faster each split toward their', es: 'crece más rápido cada split hacia su' },
  'da academia? Não dá pra desfazer.': { en: 'from academy? Cannot be undone.', es: 'de la academia? No se puede deshacer.' },
  'de 3 · fase Suíça': { en: 'of 3 · Swiss stage', es: 'de 3 · fase Suiza' },
  'de caixa': { en: 'cash', es: 'de caja' },
  'de evolução na carreira': { en: 'of career growth', es: 'de evolución en la carrera' },
  'de graça': { en: 'for free', es: 'gratis' },
  'de graça por fim de contrato. Reforce o elenco no mercado.': { en: 'for free due to expired contracts. Reinforce the roster in the market.', es: 'gratis por fin de contrato. Refuerza el elenco en el mercado.' },
  'do VRS mundial': { en: 'of the world VRS', es: 'del VRS mundial' },
  'do ranking VRS mundial': { en: 'of the world VRS ranking', es: 'del ranking VRS mundial' },
  'do ranking VRS mundial garantem a vaga': { en: 'of the world VRS ranking secure the spot', es: 'del ranking VRS mundial aseguran el spot' },
  'dominando o cenário': { en: 'dominating the scene', es: 'dominando la escena' },
  'dupla eliminação · top 2 avançam': { en: 'double elimination · top 2 advance', es: 'doble eliminación · top 2 avanzan' },
  'dá vaga no Major.': { en: 'gives a Major spot.', es: 'da un spot en el Major.' },
  'e': { en: 'and', es: 'y' },
  'elenco OVR': { en: 'roster OVR', es: 'plantilla OVR' },
  'elenco te dão': { en: 'roster give you', es: 'plantilla te dan' },
  'em ascensão': { en: 'on the rise', es: 'en ascenso' },
  'em dinheiro + sua troca': { en: 'in cash + your swap', es: 'en efectivo + tu intercambio' },
  'está em outro nível nesse split. Provavelmente o melhor do mundo agora. 🔥': { en: 'is on another level this split. Probably the best in the world right now. 🔥', es: 'está en otro nivel en este split. Probablemente el mejor del mundo ahora. 🔥' },
  'ex: ASTR': { en: 'e.g.: ASTR', es: 'p.ej: ASTR' },
  'ex: Astro Esports': { en: 'e.g.: Astro Esports', es: 'p.ej: Astro Esports' },
  'fase Suíça': { en: 'Swiss stage', es: 'fase Suiza' },
  'fase de grupos (GSL)': { en: 'group stage (GSL)', es: 'fase de grupos (GSL)' },
  'fecha a temporada (a cada': { en: 'closes the season (every', es: 'cierra la temporada (cada' },
  'fechar patrocínios e disputar os circuitos rumo ao Major. Sem lendas do': { en: 'secure sponsorships and compete in circuits towards the Major. No legends from', es: 'asegurar patrocinios y competir en circuitos hacia el Major. Sin leyendas del' },
  'fim do split': { en: 'end of split', es: 'fin del split' },
  'foco 🎯': { en: 'focus', es: 'enfoque' },
  'folha pesada': { en: 'high payroll', es: 'nómina pesada' },
  'forte.': { en: 'strong.', es: 'fuerte.' },
  'função': { en: 'role', es: 'rol' },
  'fãs': { en: 'fans', es: 'fans' },
  'garantem a vaga. Você está em': { en: 'secure the spot. You\'re in', es: 'aseguran el spot. Estás en' },
  'insatisfeitos': { en: 'unhappy', es: 'insatisfechos' },
  'jogador(es).': { en: 'player(s).', es: 'jugador(es).' },
  'jogadores': { en: 'players', es: 'jugadores' },
  'jogadores)': { en: 'players)', es: 'jugadores)' },
  'jovem em ascensão': { en: 'rising talent', es: 'joven en ascensión' },
  'já comprometido': { en: 'already committed', es: 'ya comprometido' },
  'já contratado': { en: 'already signed', es: 'ya contratado' },
  'levantou a taça e o povo foi à loucura. MERECIDO. 🐐🏆': { en: 'lifted the trophy and the crowd went wild. DESERVED. 🐐🏆', es: 'levantó la taça y la multitud enloqueció. MERECIDO. 🐐🏆' },
  'levantou o troféu do Major. O nome entrou para a história do CS.': { en: 'lifted the Major trophy. The name went down in CS history.', es: 'levantó el trofeo del Major. El nombre entró en la historia del CS.' },
  'mais verba': { en: 'more budget', es: 'más presupuesto' },
  'mapas em treino': { en: 'maps in training', es: 'mapas en entrenamiento' },
  'mata-mata': { en: 'knockout', es: 'eliminación directa' },
  'menos caixa': { en: 'less cash', es: 'menos caja' },
  'metas': { en: 'goals', es: 'objetivos' },
  'minha quarta': { en: 'my quarterfinals', es: 'mis cuartos' },
  'minha semi': { en: 'my semis', es: 'mis semis' },
  'mudou: agora é da': { en: 'changed: now plays for', es: 'cambió: ahora es de' },
  'neste split': { en: 'this split', es: 'este split' },
  'no Major:': { en: 'at Major:', es: 'en Major:' },
  'no auge': { en: 'in their prime', es: 'en su apogeo' },
  'no mundo': { en: 'in the world', es: 'en el mundo' },
  'no mundo ·': { en: 'in the world ·', es: 'en el mundo ·' },
  'no próximo split.': { en: 'next split.', es: 'próximo split.' },
  'no total': { en: 'total', es: 'en total' },
  'no último split.': { en: 'last split.', es: 'el último split.' },
  'não está à venda. O clube não quer nem ouvir.': { en: 'is not for sale. The club won\'t even listen.', es: 'no está a la venta. El club ni siquiera quiere escuchar.' },
  'o mapa mais forte deles': { en: 'their strongest map', es: 'su mapa más fuerte' },
  'ofereceu': { en: 'offered', es: 'ofreció' },
  'oferta de': { en: 'offer of', es: 'oferta de' },
  'onde têm dificuldade': { en: 'where they struggle', es: 'donde tienen dificultad' },
  'org de elite': { en: 'elite org', es: 'org de élite' },
  'org real': { en: 'real org', es: 'org real' },
  'orgs sem': { en: 'orgs without', es: 'orgs sin' },
  'ou': { en: 'or', es: 'o' },
  'ou criar uma org fictícia do zero →': { en: 'or create a fictional org from scratch →', es: 'o crear una org ficticia desde cero →' },
  'ou o jogador sai': { en: 'or the player leaves', es: 'o el jugador se va' },
  'paiN Gaming: a tradição': { en: 'paiN Gaming: the tradition', es: 'paiN Gaming: la tradición' },
  'para cada jogador antes de confirmar.': { en: 'for each player before confirming.', es: 'para cada jugador antes de confirmar.' },
  'para comandar. Cada uma tem um contexto:': { en: 'to command. Each one has a context:', es: 'para comandar. Cada una tiene un contexto:' },
  'para disputar este circuito. Suba vencendo o seu tier atual.': { en: 'to enter this circuit. Climb by winning your current tier.', es: 'para ingresar a este circuito. Sube ganando tu tier actual.' },
  'para montar 5 jogadores + coach,': { en: 'to build 5 players + coach,', es: 'para construir 5 jugadores + entrenador,' },
  'passado: o desafio é construir do zero.': { en: 'the past: the challenge is to build from zero.', es: 'pasado: el desafío es construir desde cero.' },
  'pedida': { en: 'asking', es: 'pedida' },
  'pelo': { en: 'for', es: 'por' },
  'perderam': { en: 'lost', es: 'perdieron' },
  'perdeu': { en: 'lost', es: 'perdió' },
  'por split; os outros decaem um pouco. É de propósito: ninguém é forte em todos, mas dá pra montar um pool sólido.': { en: 'per split; the others decay a bit. It\'s by design: no one is strong on every map, but you can build a solid pool.', es: 'por split; los demás decaen un poco. Es a propósito: nadie es fuerte en todos, pero puedes armar un pool sólido.' },
  'potencial': { en: 'potential', es: 'potencial' },
  'pra montar do zero.': { en: 'to build from scratch.', es: 'para construir desde cero.' },
  'precisa repor no mercado. Segurar mantém a': { en: 'need to replace on the market. Holding keeps', es: 'necesitas reponer en el mercado. Sostener mantiene' },
  'promova ao elenco': { en: 'promote to roster', es: 'promover a plantilla' },
  'prospectos': { en: 'prospects', es: 'prospectos' },
  'prêmio': { en: 'prize', es: 'premio' },
  'prêmio na': { en: 'prize at', es: 'premio en' },
  'prêmio ×': { en: 'prize ×', es: 'premio ×' },
  'próprias. O elenco e o técnico já vêm prontos; cumpra os objetivos do desafio ao longo da campanha.': { en: 'of its own. Roster and coach are ready; fulfill the challenge\'s goals throughout the campaign.', es: 'propios. La plantilla y técnico ya están listos; cumple los objetivos del desafío durante la campaña.' },
  'próxima janela': { en: 'next window', es: 'próxima ventana' },
  'quer': { en: 'wants', es: 'quiere' },
  'quer o seu': { en: 'wants your', es: 'quiere tu' },
  'receita por split:': { en: 'income per split:', es: 'ingresos por split:' },
  'rendimento. Veteranos cobram mais minutos de treino.': { en: 'form. Veterans demand more training time.', es: 'rendimiento. Los veteranos exigen más tiempo de entrenamiento.' },
  'renove (custa 1 salário)': { en: 'renew (costs 1 wage)', es: 'renueva (cuesta 1 salario)' },
  'renovável': { en: 'renewable', es: 'renovable' },
  'saiu de graça. Reforce o elenco no mercado.': { en: 'left for free. Reinforce your roster in the market.', es: 'se fue gratis. Refuerza tu plantilla en el mercado.' },
  'saldo': { en: 'differential', es: 'diferencial' },
  'salário': { en: 'wage', es: 'salario' },
  'sem caixa': { en: 'no cash', es: 'sin caja' },
  'sem elenco': { en: 'no roster', es: 'sin plantilla' },
  'sem time': { en: 'no team', es: 'sin equipo' },
  'sem troféu. calma que ano que vem é nosso 😅🙏': { en: 'no trophy. chill, next year is ours 😅🙏', es: 'sin trofeo. tranqui que el año que viene es nuestro 😅🙏' },
  'seu': { en: 'your', es: 'tu' },
  'simulação rápida': { en: 'quick simulation', es: 'simulación rápida' },
  'só elencos CS2': { en: 'CS2 rosters only', es: 'solo plantillas CS2' },
  'tempos atuais': { en: 'current era', es: 'tiempos actuales' },
  'top 2 de cada grupo vão ao mata-mata': { en: 'top 2 from each group advance to playoffs', es: 'top 2 de cada grupo van al mata-mata' },
  'vaga': { en: 'spot', es: 'plaza' },
  'vagas': { en: 'spots', es: 'plazas' },
  'vem subindo no ranking e promete brigar lá em cima. Time pra acompanhar. 📈': { en: 'is climbing the ranking and looks set to fight up top. A team to watch. 📈', es: 'viene subiendo en el ranking y promete pelear arriba. Equipo para seguir. 📈' },
  'venceu o': { en: 'won the', es: 'ganó el' },
  'vendido pra': { en: 'sold to', es: 'vendido a' },
  'veterano em declínio': { en: 'veteran in decline', es: 'veterano en declive' },
  'você joga aqui': { en: 'you play here', es: 'juegas aquí' },
  'vão ao Major.': { en: 'go to the Major.', es: 'van al Major.' },
  'vão pro': { en: 'go to the', es: 'van al' },
  '{league.name} - split encerrado': { en: '{league.name} - split ended', es: '{league.name} - split finalizado' },
  '{save.org?.name} caiu na semifinal': { en: '{save.org?.name} fell in the semifinal', es: '{save.org?.name} cayó en la semifinal' },
  '{save.org?.name} terminou em {pos}º na fase de pontos': { en: '{save.org?.name} finished {pos}th in the group stage', es: '{save.org?.name} terminó en {pos}º en la fase de puntos' },
  '{save.org?.name} é CAMPEÃO do {save.circuit?.name ?? \'circuito\'}!': { en: '{save.org?.name} is CHAMPION of the {save.circuit?.name ?? \'circuit\'}!', es: '¡{save.org?.name} es CAMPEÓN del {save.circuit?.name ?? \'circuito\'}!' },
  '{save.org?.name}: vice-campeão (perdeu a final)': { en: '{save.org?.name}: runner-up (lost the final)', es: '{save.org?.name}: subcampeón (perdió la final)' },
  '· bônus +': { en: '· bonus +', es: '· bono +' },
  '· caixa': { en: '· cash', es: '· caja' },
  '· dupla eliminação · top 2 avançam': { en: '· double elimination · top 2 advance', es: '· doble eliminación · top 2 avanzan' },
  '· fase de grupos (GSL) · top 2 de cada grupo vão ao mata-mata': { en: '· group stage (GSL) · top 2 of each group go to the playoffs', es: '· fase de grupos (GSL) · top 2 de cada grupo van a playoffs' },
  '· sem caixa': { en: '· no cash', es: '· sin caja' },
  '· simulação rápida': { en: '· quick sim', es: '· simulación rápida' },
  '· top 2 avançam': { en: '· top 2 advance', es: '· top 2 avanzan' },
  '· você em': { en: '· you in', es: '· tú en' },
  '· você é': { en: '· you\'re', es: '· eres' },
  'º na tabela': { en: 'th in the table', es: 'º en la tabla' },
  'É split de Major!': { en: 'It\'s a Major split!', es: '¡Es split de Major!' },
  'é CAMPEÃO MUNDIAL!': { en: 'is WORLD CHAMPION!', es: 'es CAMPEÓN MUNDIAL!' },
  'é CAMPEÃO do': { en: 'is CHAMPION of', es: 'es CAMPEÓN de' },
  'é a': { en: 'is the', es: 'es la' },
  'é o time a temer': { en: 'is the team to fear', es: 'es el equipo a temer' },
  '← Mercado': { en: '← Market', es: '← Mercado' },
  '← Sair': { en: '← Exit', es: '← Salir' },
  '← Voltar': { en: '← Back', es: '← Volver' },
  '← Voltar ao hub': { en: '← Back to hub', es: '← Volver al hub' },
  '← Voltar ao início': { en: '← Back to Start', es: '← Volver al Inicio' },
  '↺ Resetar': { en: '↺ Reset', es: '↺ Reiniciar' },
  '★ Prestígio': { en: '★ Prestige', es: '★ Prestigio' },
  '⚠️ A diretoria está perdendo a paciência. Falhar de novo pode custar seu emprego.': { en: '⚠️ The board is losing patience. Failing again could cost you your job.', es: '⚠️ La junta está perdiendo paciencia. Fallar de nuevo podría costarte tu trabajo.' },
  '✅ Objetivo anterior cumprido': { en: '✅ Previous objective met', es: '✅ Objetivo anterior cumplido' },
  '✅ Transferências confirmadas (já valem nos elencos)': { en: '✅ Confirmed transfers (now active in rosters)', es: '✅ Transferencias confirmadas (ya vigentes en plantillas)' },
  '✓ Liberar': { en: '✓ Release', es: '✓ Liberar' },
  '✓ Renovar': { en: '✓ Renew', es: '✓ Renovar' },
  '✔ Fundar e abrir o mercado': { en: '✔ Found and open transfer market', es: '✔ Fundar y abrir el mercado' },
  '✔ Vender por': { en: '✔ Sell for', es: '✔ Vender por' },
  '✕ Limpar': { en: '✕ Clear', es: '✕ Borrar' },
  '✕ Recusar e segurar o jogador': { en: '✕ Refuse and keep the player', es: '✕ Rechazar y mantener al jugador' },
  '❌ Objetivo anterior falhou': { en: '❌ Previous objective failed', es: '❌ Objetivo anterior falló' },
  '⬆ PROMOVIDO ao {TIER_NAMES[tierResult.tier]}! Você venceu no seu nível e subiu de tier.': { en: '⬆ PROMOTED to {TIER_NAMES[tierResult.tier]}! You won at your level and climbed tiers.', es: '⬆ PROMOVIDO al {TIER_NAMES[tierResult.tier]}! Ganaste en tu nivel y subiste de tier.' },
  '⬆ Promover': { en: '⬆ Promote', es: '⬆ Promover' },
  '⬇ Eliminação (4º)': { en: '⬇ Elimination (4th)', es: '⬇ Eliminación (4º)' },
  '⬇ Rebaixado ao {TIER_NAMES[tierResult.tier]}. Terminou no fundo da tabela; recupere o nível no próximo split.': { en: '⬇ Relegated to {TIER_NAMES[tierResult.tier]}. Finished at the bottom; recover next split.', es: '⬇ Rebajado al {TIER_NAMES[tierResult.tier]}. Terminaste en el fondo; recupera el nivel en el próximo split.' },
  '🇧🇷 Brasil': { en: '🇧🇷 Brazil', es: '🇧🇷 Brasil' },
  '🌍 Cenário atual (2026)': { en: '🌍 Current scenario (2026)', es: '🌍 Escenario actual (2026)' },
  '🌍 Ranking VRS mundial': { en: '🌍 World VRS ranking', es: '🌍 Ranking VRS mundial' },
  '🌐 País (todos)': { en: '🌐 Country (all)', es: '🌐 País (todos)' },
  '🎯 Desafios de carreira': { en: '🎯 Career challenges', es: '🎯 Desafíos de carrera' },
  '🎯 Em foco': { en: '🎯 Focused', es: '🎯 En foco' },
  '🎯 em treino': { en: '🎯 in training', es: '🎯 en entrenamiento' },
  '🎯 foco de treino': { en: '🎯 training focus', es: '🎯 foco de entrenamiento' },
  '🏆 A Premiação do Top 20 HLTV fecha a temporada (a cada {MAJOR_EVERY} campeonatos) — a próxima é no Split {nextMajorSplit}. Ainda não acabou a temporada.': { en: '🏆 The Top 20 HLTV Award closes the season (every {MAJOR_EVERY} tournaments) — next is at Split {nextMajorSplit}. Season isn\'t over yet.', es: '🏆 La Premiación del Top 20 HLTV cierra la temporada (cada {MAJOR_EVERY} campeonatos) — la próxima es en Split {nextMajorSplit}. La temporada aún no ha terminado.' },
  '🏆 Campeão': { en: '🏆 Champion', es: '🏆 Campeón' },
  '🏆 Cerimônia do Top 20 HLTV — Temporada {seasonNo}': { en: '🏆 Top 20 HLTV Ceremony — Season {seasonNo}', es: '🏆 Ceremonia del Top 20 HLTV — Temporada {seasonNo}' },
  '🏆 Troféu': { en: '🏆 Trophy', es: '🏆 Trofeo' },
  '🏛️ Diretoria': { en: '🏛️ Board', es: '🏛️ Directiva' },
  '📄 Contrato vencido:': { en: '📄 Expired contract:', es: '📄 Contrato vencido:' },
  '📋 Playbook tático': { en: '📋 Tactical playbook', es: '📋 Playbook táctico' },
  '📝 Renovação de contratos': { en: '📝 Contract renewals', es: '📝 Renovación de contratos' },
  '📨 Propostas pelos seus jogadores': { en: '📨 Offers for your players', es: '📨 Ofertas por tus jugadores' },
  '🔍 Relatório do olheiro': { en: '🔍 Scout report', es: '🔍 Informe del scout' },
  '🔍 Revelar prospecto': { en: '🔍 Scout prospect', es: '🔍 Revelar prospecto' },
  '🔒 Você precisa estar no': { en: '🔒 You need to be in', es: '🔒 Necesitas estar en' },
  '🔒 até Split': { en: '🔒 until Split', es: '🔒 hasta el Split' },
  '🗺️ Treino de mapa': { en: '🗺️ Map training', es: '🗺️ Entrenamiento de mapa' },
  '🤝 Negociações · você fecha agora, o jogador entra na': { en: '🤝 Negotiations · you close now, player joins', es: '🤝 Negociaciones · cierras ahora, el jugador entra en' },
};
