// [fase 4 · frente EDITOR] Textos do editor de base e da escolha da base na
// Carreira (chave = PT → EN/ES). Entra em CAREER_STR (career-strings.ts);
// chaves que já existiam lá continuam valendo as de lá.
export const EDITOR_STR: Record<string, { en: string; es: string }> = {
  // editor · gravação e ações
  "Sem espaço neste navegador: a última alteração não foi gravada. Exporte a base em JSON para não perder o trabalho.": { en: "No space left in this browser: the last change wasn't saved. Export the database as JSON so you don't lose your work.", es: "No queda espacio en este navegador: el último cambio no se guardó. Exporta la base en JSON para no perder el trabajo." },
  "Este navegador não deixa gravar dados. Exporte a base em JSON para não perder o trabalho.": { en: "This browser doesn't allow saving data. Export the database as JSON so you don't lose your work.", es: "Este navegador no permite guardar datos. Exporta la base en JSON para no perder el trabajo." },
  "Base grande demais (limite de 256 KB). Desfaça algumas edições ou divida em duas bases.": { en: "Database too large (256 KB limit). Undo some edits or split it into two databases.", es: "Base demasiado grande (límite de 256 KB). Deshaz algunas ediciones o divídela en dos bases." },
  "Jogador criado": { en: "Player created", es: "Jugador creado" },
  "Jogador salvo": { en: "Player saved", es: "Jugador guardado" },
  "Time criado": { en: "Team created", es: "Equipo creado" },
  "Time salvo": { en: "Team saved", es: "Equipo guardado" },
  "Minha base": { en: "My database", es: "Mi base" },
  "Base criada": { en: "Database created", es: "Base creada" },
  "cópia": { en: "copy", es: "copia" },
  "Base duplicada": { en: "Database duplicated", es: "Base duplicada" },
  "Apagar base?": { en: "Delete database?", es: "¿Borrar la base?" },
  "as carreiras que já usam esta base continuam com a cópia delas. Não tem volta.": { en: "careers already using this database keep their own copy. This can't be undone.", es: "las carreras que ya usan esta base mantienen su copia. No se puede deshacer." },
  "Base apagada": { en: "Database deleted", es: "Base borrada" },
  "Base exportada": { en: "Database exported", es: "Base exportada" },
  "Não foi possível exportar neste navegador.": { en: "Couldn't export in this browser.", es: "No se pudo exportar en este navegador." },
  "Base importada": { en: "Database imported", es: "Base importada" },
  "Jogador restaurado": { en: "Player restored", es: "Jugador restaurado" },
  "Jogador apagado": { en: "Player deleted", es: "Jugador borrado" },
  "Time restaurado": { en: "Team restored", es: "Equipo restaurado" },
  "Time apagado": { en: "Team deleted", es: "Equipo borrado" },

  // editor · listas e filtros
  "Editado": { en: "Edited", es: "Editado" },
  "Novo": { en: "New", es: "Nuevo" },
  "Jogador": { en: "Player", es: "Jugador" },
  "Sem time": { en: "No team", es: "Sin equipo" },
  "Função": { en: "Role", es: "Rol" },
  "Idade": { en: "Age", es: "Edad" },
  "CA": { en: "CA", es: "CA" },
  "PA": { en: "PA", es: "PA" },
  "Tag": { en: "Tag", es: "Tag" },
  "Elenco": { en: "Roster", es: "Plantilla" },
  "Entros.": { en: "Chem.", es: "Química" },
  "Técnico": { en: "Coach", es: "Entrenador" },
  "Times": { en: "Teams", es: "Equipos" },
  "time": { en: "team", es: "equipo" },
  "jogadores": { en: "players", es: "jugadores" },
  "Nenhuma base aberta": { en: "No database open", es: "Ninguna base abierta" },
  "Criar ou abrir uma base": { en: "Create or open a database", es: "Crear o abrir una base" },
  "Crie uma base (ela começa igual à oficial) ou importe um arquivo JSON para editar jogadores e times.": { en: "Create a database (it starts identical to the official one) or import a JSON file to edit players and teams.", es: "Crea una base (empieza igual a la oficial) o importa un archivo JSON para editar jugadores y equipos." },
  "problema nesta base": { en: "problem in this database", es: "problema en esta base" },
  "problemas nesta base": { en: "problems in this database", es: "problemas en esta base" },
  "Ver": { en: "View", es: "Ver" },
  "Enquanto houver erro, esta base não aparece para uma carreira nova.": { en: "While there are errors, this database won't be offered for a new career.", es: "Mientras haya errores, esta base no aparece para una carrera nueva." },
  "Adicionar jogador": { en: "Add player", es: "Añadir jugador" },
  "Buscar por nick ou nome…": { en: "Search by nick or name…", es: "Buscar por nick o nombre…" },
  "Buscar jogador": { en: "Search player", es: "Buscar jugador" },
  "Todos os times": { en: "All teams", es: "Todos los equipos" },
  "Sem time (free agent)": { en: "No team (free agent)", es: "Sin equipo (agente libre)" },
  "Região": { en: "Region", es: "Región" },
  "Todas as regiões": { en: "All regions", es: "Todas las regiones" },
  "Editados": { en: "Edited", es: "Editados" },
  "Novos": { en: "New", es: "Nuevos" },
  "Jogadores da base": { en: "Database players", es: "Jugadores de la base" },
  "Nenhum jogador com esses filtros": { en: "No players match these filters", es: "Ningún jugador con estos filtros" },
  "Mostrar mais": { en: "Show more", es: "Mostrar más" },
  "Adicionar time": { en: "Add team", es: "Añadir equipo" },
  "Buscar por nome ou tag…": { en: "Search by name or tag…", es: "Buscar por nombre o tag…" },
  "Buscar time": { en: "Search team", es: "Buscar equipo" },
  "Times da base": { en: "Database teams", es: "Equipos de la base" },
  "Nenhum time com esses filtros": { en: "No teams match these filters", es: "Ningún equipo con estos filtros" },
  "Buscar jogador ou time da base…": { en: "Search a player or team in the database…", es: "Buscar jugador o equipo de la base…" },

  // editor · bases, importação, validação
  "Suas bases": { en: "Your databases", es: "Tus bases" },
  "Cada base guarda só o que você mudou em cima da base oficial (elencos reais + ajustes da equipe). Ela fica neste aparelho, fora do save; uma carreira nova escolhe a base na criação e guarda uma cópia.": { en: "Each database stores only what you changed on top of the official one (real rosters + the team's adjustments). It lives on this device, outside your save; a new career picks the database when it's created and keeps a copy.", es: "Cada base guarda solo lo que cambiaste sobre la base oficial (plantillas reales + ajustes del equipo). Vive en este dispositivo, fuera de la partida; una carrera nueva elige la base al crearse y guarda una copia." },
  "Nenhuma base ainda": { en: "No databases yet", es: "Aún no hay bases" },
  "Dê um nome e crie a primeira, ou importe um arquivo.": { en: "Give it a name and create the first one, or import a file.", es: "Ponle un nombre y crea la primera, o importa un archivo." },
  "Nome da base": { en: "Database name", es: "Nombre de la base" },
  "Válida": { en: "Valid", es: "Válida" },
  "erros": { en: "errors", es: "errores" },
  "Editando": { en: "Editing", es: "Editando" },
  "Renomear": { en: "Rename", es: "Renombrar" },
  "Duplicar": { en: "Duplicate", es: "Duplicar" },
  "Exportar": { en: "Export", es: "Exportar" },
  "Nova base": { en: "New database", es: "Nueva base" },
  "Nome da base (ex.: Minha liga)": { en: "Database name (e.g. My league)", es: "Nombre de la base (ej.: Mi liga)" },
  "Nome da nova base": { en: "New database name", es: "Nombre de la nueva base" },
  "Criar base": { en: "Create database", es: "Crear base" },
  "Limite de 5 bases neste aparelho: apague ou exporte uma para criar outra.": { en: "Limit of 5 databases on this device: delete or export one to create another.", es: "Límite de 5 bases en este dispositivo: borra o exporta una para crear otra." },
  "Importar base (JSON)": { en: "Import database (JSON)", es: "Importar base (JSON)" },
  "Arquivo exportado pelo editor do Road to Major, até 1 MB. Tudo é validado antes de entrar: nada quebra o jogo.": { en: "A file exported by the Road to Major editor, up to 1 MB. Everything is validated before it goes in: nothing breaks the game.", es: "Archivo exportado por el editor de Road to Major, hasta 1 MB. Todo se valida antes de entrar: nada rompe el juego." },
  "Escolher arquivo": { en: "Choose file", es: "Elegir archivo" },
  "Ou cole o JSON": { en: "Or paste the JSON", es: "O pega el JSON" },
  "JSON da base": { en: "Database JSON", es: "JSON de la base" },
  "Validar": { en: "Validate", es: "Validar" },
  "Pronta para importar": { en: "Ready to import", es: "Lista para importar" },
  "Importar": { en: "Import", es: "Importar" },
  "avisos": { en: "warnings", es: "avisos" },
  "Arquivo recusado": { en: "File rejected", es: "Archivo rechazado" },
  "Validação": { en: "Validation", es: "Validación" },
  "Abra uma base para ver a validação.": { en: "Open a database to see its validation.", es: "Abre una base para ver la validación." },
  "Base válida: pode ser escolhida numa carreira nova.": { en: "Valid database: it can be chosen for a new career.", es: "Base válida: se puede elegir en una carrera nueva." },
  "Bases": { en: "Databases", es: "Bases" },
  "Editor de base": { en: "Database editor", es: "Editor de base" },
  "Nova carreira": { en: "New career", es: "Nueva carrera" },
  "Voltar para a carreira": { en: "Back to the career", es: "Volver a la carrera" },
  "Sair": { en: "Exit", es: "Salir" },
  "Voltar ao início": { en: "Back to the home screen", es: "Volver al inicio" },

  // ficha do jogador
  "Novo jogador": { en: "New player", es: "Nuevo jugador" },
  "Editar jogador": { en: "Edit player", es: "Editar jugador" },
  "Restaurar original": { en: "Restore original", es: "Restaurar original" },
  "Apagar jogador": { en: "Delete player", es: "Borrar jugador" },
  "Criar jogador": { en: "Create player", es: "Crear jugador" },
  "Outros": { en: "Others", es: "Otros" },
  "Função secundária": { en: "Secondary role", es: "Rol secundario" },
  "Nenhuma": { en: "None", es: "Ninguno" },
  "O nick é obrigatório (até 24 letras).": { en: "The nick is required (up to 24 characters).", es: "El nick es obligatorio (hasta 24 letras)." },
  "Habilidade": { en: "Ability", es: "Habilidad" },
  "recalculado": { en: "recalculated", es: "recalculado" },
  "PA abaixo do CA: vale o CA": { en: "PA below CA: CA is used", es: "PA por debajo del CA: vale el CA" },
  "Atributos": { en: "Attributes", es: "Atributos" },
  "Ocultos": { en: "Hidden", es: "Ocultos" },
  "No jogo, os ocultos só aparecem por relatório de olheiro e pelo comportamento.": { en: "In the game, hidden attributes only show up through scout reports and behaviour.", es: "En el juego, los ocultos solo aparecen por informes de ojeador y por el comportamiento." },
  "Não dá para salvar assim": { en: "Can't save like this", es: "No se puede guardar así" },

  // ficha do time
  "Novo time": { en: "New team", es: "Nuevo equipo" },
  "Editar time": { en: "Edit team", es: "Editar equipo" },
  "Apagar time": { en: "Delete team", es: "Borrar equipo" },
  "Criar time": { en: "Create team", es: "Crear equipo" },
  "Nome do time": { en: "Team name", es: "Nombre del equipo" },
  "Cores": { en: "Colours", es: "Colores" },
  "Cor principal": { en: "Primary colour", es: "Color principal" },
  "Cor secundária": { en: "Secondary colour", es: "Color secundario" },
  "País da organização": { en: "Organisation country", es: "País de la organización" },
  "Entrosamento": { en: "Chemistry", es: "Química" },
  "Nome e tag (até 5 letras) são obrigatórios.": { en: "Name and tag (up to 5 letters) are required.", es: "Nombre y tag (hasta 5 letras) son obligatorios." },
  "Estilo": { en: "Style", es: "Estilo" },
  "Nota do técnico": { en: "Coach rating", es: "Nota del entrenador" },
  "Os 5 primeiros são os titulares. Quem sai do elenco vai para o mercado livre.": { en: "The first 5 are the starters. Anyone removed from the roster goes to free agency.", es: "Los 5 primeros son los titulares. Quien sale de la plantilla pasa al mercado libre." },
  "vem de": { en: "from", es: "viene de" },
  "mercado livre": { en: "free agency", es: "mercado libre" },
  "gerado": { en: "generated", es: "generado" },
  "Subir": { en: "Move up", es: "Subir" },
  "Tirar do elenco": { en: "Remove from roster", es: "Quitar de la plantilla" },
  "O elenco precisa de 5 a 10 jogadores.": { en: "The roster needs 5 to 10 players.", es: "La plantilla necesita de 5 a 10 jugadores." },
  "Buscar jogador para o elenco…": { en: "Search a player for the roster…", es: "Buscar jugador para la plantilla…" },
  "Buscar jogador para o elenco": { en: "Search a player for the roster", es: "Buscar jugador para la plantilla" },
  "Gerar jovens": { en: "Generate youngsters", es: "Generar jóvenes" },
  "Trazer": { en: "Bring in", es: "Traer" },
  "Nenhum jogador encontrado.": { en: "No players found.", es: "Ningún jugador encontrado." },
  "Editado nesta base": { en: "Edited in this database", es: "Editado en esta base" },
  "Tático": { en: "Tactical", es: "Táctico" },
  "Agressivo": { en: "Aggressive", es: "Agresivo" },
  "Disciplinador": { en: "Disciplinarian", es: "Disciplinario" },

  // resumo de uma base
  "jogador editado": { en: "player edited", es: "jugador editado" },
  "jogadores editados": { en: "players edited", es: "jugadores editados" },
  "time editado": { en: "team edited", es: "equipo editado" },
  "times editados": { en: "teams edited", es: "equipos editados" },
  "jogador novo": { en: "new player", es: "jugador nuevo" },
  "jogadores novos": { en: "new players", es: "jugadores nuevos" },
  "time novo": { en: "new team", es: "equipo nuevo" },
  "times novos": { en: "new teams", es: "equipos nuevos" },
  "Sem alterações ainda": { en: "No changes yet", es: "Sin cambios todavía" },

  // escolha da base na Carreira
  "Base de dados do mundo": { en: "World database", es: "Base de datos del mundo" },
  "Abrir editor": { en: "Open editor", es: "Abrir editor" },
  "Escolha antes de assumir um clube. A base fica congelada nesta carreira: editar ou apagar a base depois não muda o que já começou.": { en: "Choose before taking over a club. The database is frozen in this career: editing or deleting it later doesn't change what has already started.", es: "Elige antes de asumir un club. La base queda congelada en esta carrera: editarla o borrarla después no cambia lo que ya empezó." },
  "A base escolhida não está mais neste aparelho ou ficou inválida. Esta carreira usa a base oficial.": { en: "The chosen database is no longer on this device or became invalid. This career uses the official database.", es: "La base elegida ya no está en este dispositivo o quedó inválida. Esta carrera usa la base oficial." },
  "Oficial": { en: "Official", es: "Oficial" },
  "Elencos reais de setembro de 2026 com os ajustes da equipe do Road to Major": { en: "Real rosters from September 2026 with the Road to Major team's adjustments", es: "Plantillas reales de septiembre de 2026 con los ajustes del equipo de Road to Major" },
  "Corrija os erros no editor para usar esta base": { en: "Fix the errors in the editor to use this database", es: "Corrige los errores en el editor para usar esta base" },
  "Quer mexer em jogadores, times e elencos antes de começar? Crie uma base no editor.": { en: "Want to change players, teams and rosters before you start? Create a database in the editor.", es: "¿Quieres tocar jugadores, equipos y plantillas antes de empezar? Crea una base en el editor." },
  "A base de dados desta carreira não está disponível:": { en: "This career's database isn't available:", es: "La base de datos de esta carrera no está disponible:" },
  "A carreira continua na base oficial.": { en: "The career continues on the official database.", es: "La carrera continúa con la base oficial." },
  "Internacional": { en: "International", es: "Internacional" },

  // menu inicial
  "Estilo FM": { en: "FM style", es: "Estilo FM" },
  "Edite jogadores (atributos, ocultos, CA/PA), times e elencos, crie os seus e comece uma carreira com a sua base.": { en: "Edit players (attributes, hidden, CA/PA), teams and rosters, create your own and start a career with your database.", es: "Edita jugadores (atributos, ocultos, CA/PA), equipos y plantillas, crea los tuyos y empieza una carrera con tu base." },
  "Exporte e importe em JSON": { en: "Export and import as JSON", es: "Exporta e importa en JSON" },
  "Abrir": { en: "Open", es: "Abrir" },

  // validação (engine/mundo/editor.ts)
  "Atributos incompletos ou em formato inválido": { en: "Attributes incomplete or in an invalid format", es: "Atributos incompletos o con formato inválido" },
  "Atributo ausente ou não numérico": { en: "Attribute missing or not a number", es: "Atributo ausente o no numérico" },
  "Atributo fora da faixa 1–20": { en: "Attribute outside the 1–20 range", es: "Atributo fuera del rango 1–20" },
  "Atributo oculto ausente ou não numérico": { en: "Hidden attribute missing or not a number", es: "Atributo oculto ausente o no numérico" },
  "Atributo oculto fora da faixa 1–20": { en: "Hidden attribute outside the 1–20 range", es: "Atributo oculto fuera del rango 1–20" },
  "PA ausente ou não numérico": { en: "PA missing or not a number", es: "PA ausente o no numérico" },
  "PA fora da faixa 1–200": { en: "PA outside the 1–200 range", es: "PA fuera del rango 1–200" },
  "CA recalculado a partir dos atributos": { en: "CA recalculated from the attributes", es: "CA recalculado a partir de los atributos" },
  "PA abaixo do CA: subiu para o CA": { en: "PA below CA: raised to CA", es: "PA por debajo del CA: subió al CA" },
  "Técnico em formato inválido": { en: "Coach in an invalid format", es: "Entrenador con formato inválido" },
  "Técnico sem nick": { en: "Coach without a nick", es: "Entrenador sin nick" },
  "Nota do técnico ausente": { en: "Coach rating missing", es: "Nota del entrenador ausente" },
  "Nota do técnico fora da faixa 50–99": { en: "Coach rating outside the 50–99 range", es: "Nota del entrenador fuera del rango 50–99" },
  "Estilo do técnico inválido": { en: "Invalid coach style", es: "Estilo del entrenador inválido" },
  "Nome do time vazio ou longo demais": { en: "Team name empty or too long", es: "Nombre del equipo vacío o demasiado largo" },
  "Tag vazia ou com mais de 5 letras": { en: "Tag empty or longer than 5 letters", es: "Tag vacío o con más de 5 letras" },
  "País inválido (código de 2 letras)": { en: "Invalid country (2-letter code)", es: "País inválido (código de 2 letras)" },
  "Cores inválidas (duas cores #RRGGBB)": { en: "Invalid colours (two #RRGGBB colours)", es: "Colores inválidos (dos colores #RRGGBB)" },
  "Entrosamento inválido": { en: "Invalid chemistry", es: "Química inválida" },
  "Entrosamento fora da faixa 40–95": { en: "Chemistry outside the 40–95 range", es: "Química fuera del rango 40–95" },
  "Jogador do elenco não existe na base: ignorado": { en: "Roster player doesn't exist in the database: ignored", es: "Jugador de la plantilla no existe en la base: ignorado" },
  "Jogador em dois elencos": { en: "Player in two rosters", es: "Jugador en dos plantillas" },
  "Arquivo não é uma base do Road to Major": { en: "File is not a Road to Major database", es: "El archivo no es una base de Road to Major" },
  "Versão da base não suportada": { en: "Unsupported database version", es: "Versión de base no compatible" },
  "Base de origem desconhecida": { en: "Unknown source database", es: "Base de origen desconocida" },
  "Identificador da base inválido": { en: "Invalid database id", es: "Identificador de base inválido" },
  "Nome da base vazio ou longo demais": { en: "Database name empty or too long", es: "Nombre de la base vacío o demasiado largo" },
  "Lista de jogadores novos inválida": { en: "Invalid list of new players", es: "Lista de jugadores nuevos inválida" },
  "Lista de times novos inválida": { en: "Invalid list of new teams", es: "Lista de equipos nuevos inválida" },
  "Edições de jogadores inválidas": { en: "Invalid player edits", es: "Ediciones de jugadores inválidas" },
  "Edições de times inválidas": { en: "Invalid team edits", es: "Ediciones de equipos inválidas" },
  "Jogadores novos acima do limite": { en: "Too many new players", es: "Demasiados jugadores nuevos" },
  "Times novos acima do limite": { en: "Too many new teams", es: "Demasiados equipos nuevos" },
  "Edições de jogadores acima do limite": { en: "Too many player edits", es: "Demasiadas ediciones de jugadores" },
  "Edições de times acima do limite": { en: "Too many team edits", es: "Demasiadas ediciones de equipos" },
  "Jogador novo em formato inválido": { en: "New player in an invalid format", es: "Jugador nuevo con formato inválido" },
  "Id de jogador novo inválido (use cdb_p_…)": { en: "Invalid new player id (use cdb_p_…)", es: "Id de jugador nuevo inválido (usa cdb_p_…)" },
  "Id de jogador repetido": { en: "Duplicate player id", es: "Id de jugador repetido" },
  "Jogador sem nick (ou longo demais)": { en: "Player without a nick (or too long)", es: "Jugador sin nick (o demasiado largo)" },
  "Função inválida": { en: "Invalid role", es: "Rol inválido" },
  "Idade ausente": { en: "Age missing", es: "Edad ausente" },
  "Idade fora da faixa 15–45": { en: "Age outside the 15–45 range", es: "Edad fuera del rango 15–45" },
  "Time novo em formato inválido": { en: "New team in an invalid format", es: "Equipo nuevo con formato inválido" },
  "Id de time novo inválido (use cdb_t_…)": { en: "Invalid new team id (use cdb_t_…)", es: "Id de equipo nuevo inválido (usa cdb_t_…)" },
  "Id de time repetido": { en: "Duplicate team id", es: "Id de equipo repetido" },
  "Edição de jogador que não existe na base: ignorada": { en: "Edit for a player not in the database: ignored", es: "Edición de un jugador que no existe en la base: ignorada" },
  "Edição de jogador inválida": { en: "Invalid player edit", es: "Edición de jugador inválida" },
  "Nome inválido": { en: "Invalid name", es: "Nombre inválido" },
  "Função secundária inválida": { en: "Invalid secondary role", es: "Rol secundario inválido" },
  "Edição de time que não existe na base: ignorada": { en: "Edit for a team not in the database: ignored", es: "Edición de un equipo que no existe en la base: ignorada" },
  "Aposentados não são editáveis: ignorado": { en: "Retired players can't be edited: ignored", es: "Los retirados no se pueden editar: ignorado" },
  "Edição de time inválida": { en: "Invalid team edit", es: "Edición de equipo inválida" },
  "Elenco em formato inválido": { en: "Roster in an invalid format", es: "Plantilla con formato inválido" },
  "Elenco com menos de 5 jogadores": { en: "Roster with fewer than 5 players", es: "Plantilla con menos de 5 jugadores" },
  "Elenco com mais de 10 jogadores": { en: "Roster with more than 10 players", es: "Plantilla con más de 10 jugadores" },
  "Time novo sem elenco": { en: "New team without a roster", es: "Equipo nuevo sin plantilla" },
  "Base grande demais (limite de 256 KB)": { en: "Database too large (256 KB limit)", es: "Base demasiado grande (límite de 256 KB)" },
  "Arquivo não é texto": { en: "File is not text", es: "El archivo no es texto" },
  "Arquivo grande demais (limite de 1 MB)": { en: "File too large (1 MB limit)", es: "Archivo demasiado grande (límite de 1 MB)" },
  "JSON inválido": { en: "Invalid JSON", es: "JSON inválido" },
  "Já existe uma base com esse id: importada como cópia": { en: "A database with this id already exists: imported as a copy", es: "Ya existe una base con ese id: importada como copia" },
  "Não foi possível ler o arquivo": { en: "Couldn't read the file", es: "No se pudo leer el archivo" },

  // atributos ocultos e visíveis (rótulos do editor)
  "Jogo grande": { en: "Big matches", es: "Partidos grandes" },
  "Temperamento": { en: "Temperament", es: "Temperamento" },
  "Regularidade real": { en: "True consistency", es: "Regularidad real" },
  "Profissionalismo": { en: "Professionalism", es: "Profesionalismo" },
  "Propensão a lesão": { en: "Injury proneness", es: "Propensión a lesiones" },
  "Versatilidade": { en: "Versatility", es: "Versatilidad" },
  "Mira em movimento": { en: "Aim on the move", es: "Puntería en movimiento" },
  "Tap shot": { en: "Tap shot", es: "Tap shot" },
  "Spray control": { en: "Spray control", es: "Control de spray" },
  "Headshot %": { en: "Headshot %", es: "Headshot %" },
  "Crosshair placement": { en: "Crosshair placement", es: "Colocación de mira" },
  "Pre-aim": { en: "Pre-aim", es: "Pre-aim" },
  "Off-angles": { en: "Off-angles", es: "Off-angles" },
  "Game sense": { en: "Game sense", es: "Lectura de juego" },
  "Decisões": { en: "Decisions", es: "Decisiones" },
  "Antecipação": { en: "Anticipation", es: "Anticipación" },
  "Frieza": { en: "Composure", es: "Temple" },
  "Concentração": { en: "Concentration", es: "Concentración" },
  "Posicionamento": { en: "Positioning", es: "Posicionamiento" },
  "Trabalho em equipe": { en: "Teamwork", es: "Trabajo en equipo" },
  "Comunicação": { en: "Communication", es: "Comunicación" },
  "Adaptabilidade": { en: "Adaptability", es: "Adaptabilidad" },
  "Visão tática": { en: "Tactical vision", es: "Visión táctica" },
  "Reflexos": { en: "Reflexes", es: "Reflejos" },
  "Reação": { en: "Reaction", es: "Reacción" },
  "Stamina": { en: "Stamina", es: "Resistencia" },
  "Coordenação": { en: "Coordination", es: "Coordinación" },
  "APM": { en: "APM", es: "APM" },
  "Consistência": { en: "Consistency", es: "Consistencia" },
  "Américas": { en: "Americas", es: "Américas" },
  "Europa": { en: "Europe", es: "Europa" },
  "CIS": { en: "CIS", es: "CIS" },
  "Ásia": { en: "Asia", es: "Asia" },
  "Oceania": { en: "Oceania", es: "Oceanía" },
  "África": { en: "Africa", es: "África" },
};
